permissions:
  - name: EMPLOYEE_CREATE
    resource: /employee/profile
    method: [POST]
  - name: EMPLOYEE_VIEW
    resource: /employee/profile
    method: [GET]

roles:
  - name: admin
    id: 1
    description: "Admin role"
    permissions:
      - EMPLOYEE_CREATE
      - EMPLOYEE_VIEW