// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/service.proto

package grpclient

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PersonalizedCarePlanRequest struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	ClientData        *ClientData              `protobuf:"bytes,2,opt,name=client_data,json=clientData,proto3" json:"client_data,omitempty"`
	DomainDefinitions map[string]*DomainLevels `protobuf:"bytes,3,rep,name=domain_definitions,json=domainDefinitions,proto3" json:"domain_definitions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PersonalizedCarePlanRequest) Reset() {
	*x = PersonalizedCarePlanRequest{}
	mi := &file_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalizedCarePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalizedCarePlanRequest) ProtoMessage() {}

func (x *PersonalizedCarePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalizedCarePlanRequest.ProtoReflect.Descriptor instead.
func (*PersonalizedCarePlanRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *PersonalizedCarePlanRequest) GetClientData() *ClientData {
	if x != nil {
		return x.ClientData
	}
	return nil
}

func (x *PersonalizedCarePlanRequest) GetDomainDefinitions() map[string]*DomainLevels {
	if x != nil {
		return x.DomainDefinitions
	}
	return nil
}

type ClientData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Age              int32                  `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	LivingSituation  string                 `protobuf:"bytes,2,opt,name=living_situation,json=livingSituation,proto3" json:"living_situation,omitempty"`
	EducationLevel   string                 `protobuf:"bytes,3,opt,name=education_level,json=educationLevel,proto3" json:"education_level,omitempty"`
	DomainName       string                 `protobuf:"bytes,4,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	CurrentLevel     int32                  `protobuf:"varint,5,opt,name=current_level,json=currentLevel,proto3" json:"current_level,omitempty"`
	LevelDescription string                 `protobuf:"bytes,6,opt,name=level_description,json=levelDescription,proto3" json:"level_description,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClientData) Reset() {
	*x = ClientData{}
	mi := &file_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientData) ProtoMessage() {}

func (x *ClientData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientData.ProtoReflect.Descriptor instead.
func (*ClientData) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *ClientData) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *ClientData) GetLivingSituation() string {
	if x != nil {
		return x.LivingSituation
	}
	return ""
}

func (x *ClientData) GetEducationLevel() string {
	if x != nil {
		return x.EducationLevel
	}
	return ""
}

func (x *ClientData) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

func (x *ClientData) GetCurrentLevel() int32 {
	if x != nil {
		return x.CurrentLevel
	}
	return 0
}

func (x *ClientData) GetLevelDescription() string {
	if x != nil {
		return x.LevelDescription
	}
	return ""
}

type DomainLevels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Levels        map[int32]string       `protobuf:"bytes,1,rep,name=levels,proto3" json:"levels,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainLevels) Reset() {
	*x = DomainLevels{}
	mi := &file_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainLevels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainLevels) ProtoMessage() {}

func (x *DomainLevels) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainLevels.ProtoReflect.Descriptor instead.
func (*DomainLevels) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *DomainLevels) GetLevels() map[int32]string {
	if x != nil {
		return x.Levels
	}
	return nil
}

type PersonalizedCarePlanResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ClientProfile      *ClientProfile         `protobuf:"bytes,1,opt,name=client_profile,json=clientProfile,proto3" json:"client_profile,omitempty"`
	AssessmentSummary  string                 `protobuf:"bytes,2,opt,name=assessment_summary,json=assessmentSummary,proto3" json:"assessment_summary,omitempty"`
	CarePlanObjectives *CarePlanObjectives    `protobuf:"bytes,3,opt,name=care_plan_objectives,json=carePlanObjectives,proto3" json:"care_plan_objectives,omitempty"`
	Interventions      *Interventions         `protobuf:"bytes,4,opt,name=interventions,proto3" json:"interventions,omitempty"`
	ResourcesRequired  []string               `protobuf:"bytes,5,rep,name=resources_required,json=resourcesRequired,proto3" json:"resources_required,omitempty"`
	SuccessMetrics     []*SuccessMetric       `protobuf:"bytes,6,rep,name=success_metrics,json=successMetrics,proto3" json:"success_metrics,omitempty"`
	RiskFactors        []*RiskFactor          `protobuf:"bytes,7,rep,name=risk_factors,json=riskFactors,proto3" json:"risk_factors,omitempty"`
	SupportNetwork     []*SupportRole         `protobuf:"bytes,8,rep,name=support_network,json=supportNetwork,proto3" json:"support_network,omitempty"`
	ReviewSchedule     *ReviewSchedule        `protobuf:"bytes,9,opt,name=review_schedule,json=reviewSchedule,proto3" json:"review_schedule,omitempty"`
	EmergencyProtocols []string               `protobuf:"bytes,10,rep,name=emergency_protocols,json=emergencyProtocols,proto3" json:"emergency_protocols,omitempty"`
	TransitionCriteria *TransitionCriteria    `protobuf:"bytes,11,opt,name=transition_criteria,json=transitionCriteria,proto3" json:"transition_criteria,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PersonalizedCarePlanResponse) Reset() {
	*x = PersonalizedCarePlanResponse{}
	mi := &file_proto_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalizedCarePlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalizedCarePlanResponse) ProtoMessage() {}

func (x *PersonalizedCarePlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalizedCarePlanResponse.ProtoReflect.Descriptor instead.
func (*PersonalizedCarePlanResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *PersonalizedCarePlanResponse) GetClientProfile() *ClientProfile {
	if x != nil {
		return x.ClientProfile
	}
	return nil
}

func (x *PersonalizedCarePlanResponse) GetAssessmentSummary() string {
	if x != nil {
		return x.AssessmentSummary
	}
	return ""
}

func (x *PersonalizedCarePlanResponse) GetCarePlanObjectives() *CarePlanObjectives {
	if x != nil {
		return x.CarePlanObjectives
	}
	return nil
}

func (x *PersonalizedCarePlanResponse) GetInterventions() *Interventions {
	if x != nil {
		return x.Interventions
	}
	return nil
}

func (x *PersonalizedCarePlanResponse) GetResourcesRequired() []string {
	if x != nil {
		return x.ResourcesRequired
	}
	return nil
}

func (x *PersonalizedCarePlanResponse) GetSuccessMetrics() []*SuccessMetric {
	if x != nil {
		return x.SuccessMetrics
	}
	return nil
}

func (x *PersonalizedCarePlanResponse) GetRiskFactors() []*RiskFactor {
	if x != nil {
		return x.RiskFactors
	}
	return nil
}

func (x *PersonalizedCarePlanResponse) GetSupportNetwork() []*SupportRole {
	if x != nil {
		return x.SupportNetwork
	}
	return nil
}

func (x *PersonalizedCarePlanResponse) GetReviewSchedule() *ReviewSchedule {
	if x != nil {
		return x.ReviewSchedule
	}
	return nil
}

func (x *PersonalizedCarePlanResponse) GetEmergencyProtocols() []string {
	if x != nil {
		return x.EmergencyProtocols
	}
	return nil
}

func (x *PersonalizedCarePlanResponse) GetTransitionCriteria() *TransitionCriteria {
	if x != nil {
		return x.TransitionCriteria
	}
	return nil
}

type ClientProfile struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Age              int32                  `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	LivingSituation  string                 `protobuf:"bytes,2,opt,name=living_situation,json=livingSituation,proto3" json:"living_situation,omitempty"`
	EducationLevel   string                 `protobuf:"bytes,3,opt,name=education_level,json=educationLevel,proto3" json:"education_level,omitempty"`
	AssessmentDomain string                 `protobuf:"bytes,4,opt,name=assessment_domain,json=assessmentDomain,proto3" json:"assessment_domain,omitempty"`
	CurrentLevel     int32                  `protobuf:"varint,5,opt,name=current_level,json=currentLevel,proto3" json:"current_level,omitempty"`
	LevelDescription string                 `protobuf:"bytes,6,opt,name=level_description,json=levelDescription,proto3" json:"level_description,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClientProfile) Reset() {
	*x = ClientProfile{}
	mi := &file_proto_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientProfile) ProtoMessage() {}

func (x *ClientProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientProfile.ProtoReflect.Descriptor instead.
func (*ClientProfile) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *ClientProfile) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *ClientProfile) GetLivingSituation() string {
	if x != nil {
		return x.LivingSituation
	}
	return ""
}

func (x *ClientProfile) GetEducationLevel() string {
	if x != nil {
		return x.EducationLevel
	}
	return ""
}

func (x *ClientProfile) GetAssessmentDomain() string {
	if x != nil {
		return x.AssessmentDomain
	}
	return ""
}

func (x *ClientProfile) GetCurrentLevel() int32 {
	if x != nil {
		return x.CurrentLevel
	}
	return 0
}

func (x *ClientProfile) GetLevelDescription() string {
	if x != nil {
		return x.LevelDescription
	}
	return ""
}

type CarePlanObjectives struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ShortTermGoals  []*Goal                `protobuf:"bytes,1,rep,name=short_term_goals,json=shortTermGoals,proto3" json:"short_term_goals,omitempty"`
	MediumTermGoals []*Goal                `protobuf:"bytes,2,rep,name=medium_term_goals,json=mediumTermGoals,proto3" json:"medium_term_goals,omitempty"`
	LongTermGoals   []*Goal                `protobuf:"bytes,3,rep,name=long_term_goals,json=longTermGoals,proto3" json:"long_term_goals,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CarePlanObjectives) Reset() {
	*x = CarePlanObjectives{}
	mi := &file_proto_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarePlanObjectives) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarePlanObjectives) ProtoMessage() {}

func (x *CarePlanObjectives) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarePlanObjectives.ProtoReflect.Descriptor instead.
func (*CarePlanObjectives) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{5}
}

func (x *CarePlanObjectives) GetShortTermGoals() []*Goal {
	if x != nil {
		return x.ShortTermGoals
	}
	return nil
}

func (x *CarePlanObjectives) GetMediumTermGoals() []*Goal {
	if x != nil {
		return x.MediumTermGoals
	}
	return nil
}

func (x *CarePlanObjectives) GetLongTermGoals() []*Goal {
	if x != nil {
		return x.LongTermGoals
	}
	return nil
}

type Goal struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timeframe       string                 `protobuf:"bytes,1,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	GoalTitle       string                 `protobuf:"bytes,2,opt,name=goal_title,json=goalTitle,proto3" json:"goal_title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SpecificActions []string               `protobuf:"bytes,4,rep,name=specific_actions,json=specificActions,proto3" json:"specific_actions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Goal) Reset() {
	*x = Goal{}
	mi := &file_proto_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Goal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goal) ProtoMessage() {}

func (x *Goal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goal.ProtoReflect.Descriptor instead.
func (*Goal) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{6}
}

func (x *Goal) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *Goal) GetGoalTitle() string {
	if x != nil {
		return x.GoalTitle
	}
	return ""
}

func (x *Goal) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Goal) GetSpecificActions() []string {
	if x != nil {
		return x.SpecificActions
	}
	return nil
}

type Interventions struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DailyActivities   []string               `protobuf:"bytes,1,rep,name=daily_activities,json=dailyActivities,proto3" json:"daily_activities,omitempty"`
	WeeklyActivities  []string               `protobuf:"bytes,2,rep,name=weekly_activities,json=weeklyActivities,proto3" json:"weekly_activities,omitempty"`
	MonthlyActivities []string               `protobuf:"bytes,3,rep,name=monthly_activities,json=monthlyActivities,proto3" json:"monthly_activities,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Interventions) Reset() {
	*x = Interventions{}
	mi := &file_proto_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interventions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interventions) ProtoMessage() {}

func (x *Interventions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interventions.ProtoReflect.Descriptor instead.
func (*Interventions) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{7}
}

func (x *Interventions) GetDailyActivities() []string {
	if x != nil {
		return x.DailyActivities
	}
	return nil
}

func (x *Interventions) GetWeeklyActivities() []string {
	if x != nil {
		return x.WeeklyActivities
	}
	return nil
}

func (x *Interventions) GetMonthlyActivities() []string {
	if x != nil {
		return x.MonthlyActivities
	}
	return nil
}

type SuccessMetric struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Metric            string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Target            string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	MeasurementMethod string                 `protobuf:"bytes,3,opt,name=measurement_method,json=measurementMethod,proto3" json:"measurement_method,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SuccessMetric) Reset() {
	*x = SuccessMetric{}
	mi := &file_proto_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessMetric) ProtoMessage() {}

func (x *SuccessMetric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessMetric.ProtoReflect.Descriptor instead.
func (*SuccessMetric) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{8}
}

func (x *SuccessMetric) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *SuccessMetric) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *SuccessMetric) GetMeasurementMethod() string {
	if x != nil {
		return x.MeasurementMethod
	}
	return ""
}

type RiskFactor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Risk          string                 `protobuf:"bytes,1,opt,name=risk,proto3" json:"risk,omitempty"`
	Mitigation    string                 `protobuf:"bytes,2,opt,name=mitigation,proto3" json:"mitigation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskFactor) Reset() {
	*x = RiskFactor{}
	mi := &file_proto_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskFactor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskFactor) ProtoMessage() {}

func (x *RiskFactor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskFactor.ProtoReflect.Descriptor instead.
func (*RiskFactor) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{9}
}

func (x *RiskFactor) GetRisk() string {
	if x != nil {
		return x.Risk
	}
	return ""
}

func (x *RiskFactor) GetMitigation() string {
	if x != nil {
		return x.Mitigation
	}
	return ""
}

type SupportRole struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Role           string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Responsibility string                 `protobuf:"bytes,2,opt,name=responsibility,proto3" json:"responsibility,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SupportRole) Reset() {
	*x = SupportRole{}
	mi := &file_proto_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportRole) ProtoMessage() {}

func (x *SupportRole) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportRole.ProtoReflect.Descriptor instead.
func (*SupportRole) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{10}
}

func (x *SupportRole) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SupportRole) GetResponsibility() string {
	if x != nil {
		return x.Responsibility
	}
	return ""
}

type ReviewSchedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Daily         string                 `protobuf:"bytes,1,opt,name=daily,proto3" json:"daily,omitempty"`
	Weekly        string                 `protobuf:"bytes,2,opt,name=weekly,proto3" json:"weekly,omitempty"`
	Monthly       string                 `protobuf:"bytes,3,opt,name=monthly,proto3" json:"monthly,omitempty"`
	Quarterly     string                 `protobuf:"bytes,4,opt,name=quarterly,proto3" json:"quarterly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewSchedule) Reset() {
	*x = ReviewSchedule{}
	mi := &file_proto_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewSchedule) ProtoMessage() {}

func (x *ReviewSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewSchedule.ProtoReflect.Descriptor instead.
func (*ReviewSchedule) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{11}
}

func (x *ReviewSchedule) GetDaily() string {
	if x != nil {
		return x.Daily
	}
	return ""
}

func (x *ReviewSchedule) GetWeekly() string {
	if x != nil {
		return x.Weekly
	}
	return ""
}

func (x *ReviewSchedule) GetMonthly() string {
	if x != nil {
		return x.Monthly
	}
	return ""
}

func (x *ReviewSchedule) GetQuarterly() string {
	if x != nil {
		return x.Quarterly
	}
	return ""
}

type TransitionCriteria struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextLevel     int32                  `protobuf:"varint,1,opt,name=next_level,json=nextLevel,proto3" json:"next_level,omitempty"`
	Requirements  []string               `protobuf:"bytes,2,rep,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionCriteria) Reset() {
	*x = TransitionCriteria{}
	mi := &file_proto_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionCriteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionCriteria) ProtoMessage() {}

func (x *TransitionCriteria) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionCriteria.ProtoReflect.Descriptor instead.
func (*TransitionCriteria) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{12}
}

func (x *TransitionCriteria) GetNextLevel() int32 {
	if x != nil {
		return x.NextLevel
	}
	return 0
}

func (x *TransitionCriteria) GetRequirements() []string {
	if x != nil {
		return x.Requirements
	}
	return nil
}

var File_proto_service_proto protoreflect.FileDescriptor

const file_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x13proto/service.proto\x12\tgrpclient\"\xa2\x02\n" +
	"\x1bPersonalizedCarePlanRequest\x126\n" +
	"\vclient_data\x18\x02 \x01(\v2\x15.grpclient.ClientDataR\n" +
	"clientData\x12l\n" +
	"\x12domain_definitions\x18\x03 \x03(\v2=.grpclient.PersonalizedCarePlanRequest.DomainDefinitionsEntryR\x11domainDefinitions\x1a]\n" +
	"\x16DomainDefinitionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.grpclient.DomainLevelsR\x05value:\x028\x01\"\xe5\x01\n" +
	"\n" +
	"ClientData\x12\x10\n" +
	"\x03age\x18\x01 \x01(\x05R\x03age\x12)\n" +
	"\x10living_situation\x18\x02 \x01(\tR\x0flivingSituation\x12'\n" +
	"\x0feducation_level\x18\x03 \x01(\tR\x0eeducationLevel\x12\x1f\n" +
	"\vdomain_name\x18\x04 \x01(\tR\n" +
	"domainName\x12#\n" +
	"\rcurrent_level\x18\x05 \x01(\x05R\fcurrentLevel\x12+\n" +
	"\x11level_description\x18\x06 \x01(\tR\x10levelDescription\"\x86\x01\n" +
	"\fDomainLevels\x12;\n" +
	"\x06levels\x18\x01 \x03(\v2#.grpclient.DomainLevels.LevelsEntryR\x06levels\x1a9\n" +
	"\vLevelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd1\x05\n" +
	"\x1cPersonalizedCarePlanResponse\x12?\n" +
	"\x0eclient_profile\x18\x01 \x01(\v2\x18.grpclient.ClientProfileR\rclientProfile\x12-\n" +
	"\x12assessment_summary\x18\x02 \x01(\tR\x11assessmentSummary\x12O\n" +
	"\x14care_plan_objectives\x18\x03 \x01(\v2\x1d.grpclient.CarePlanObjectivesR\x12carePlanObjectives\x12>\n" +
	"\rinterventions\x18\x04 \x01(\v2\x18.grpclient.InterventionsR\rinterventions\x12-\n" +
	"\x12resources_required\x18\x05 \x03(\tR\x11resourcesRequired\x12A\n" +
	"\x0fsuccess_metrics\x18\x06 \x03(\v2\x18.grpclient.SuccessMetricR\x0esuccessMetrics\x128\n" +
	"\frisk_factors\x18\a \x03(\v2\x15.grpclient.RiskFactorR\vriskFactors\x12?\n" +
	"\x0fsupport_network\x18\b \x03(\v2\x16.grpclient.SupportRoleR\x0esupportNetwork\x12B\n" +
	"\x0freview_schedule\x18\t \x01(\v2\x19.grpclient.ReviewScheduleR\x0ereviewSchedule\x12/\n" +
	"\x13emergency_protocols\x18\n" +
	" \x03(\tR\x12emergencyProtocols\x12N\n" +
	"\x13transition_criteria\x18\v \x01(\v2\x1d.grpclient.TransitionCriteriaR\x12transitionCriteria\"\xf4\x01\n" +
	"\rClientProfile\x12\x10\n" +
	"\x03age\x18\x01 \x01(\x05R\x03age\x12)\n" +
	"\x10living_situation\x18\x02 \x01(\tR\x0flivingSituation\x12'\n" +
	"\x0feducation_level\x18\x03 \x01(\tR\x0eeducationLevel\x12+\n" +
	"\x11assessment_domain\x18\x04 \x01(\tR\x10assessmentDomain\x12#\n" +
	"\rcurrent_level\x18\x05 \x01(\x05R\fcurrentLevel\x12+\n" +
	"\x11level_description\x18\x06 \x01(\tR\x10levelDescription\"\xc5\x01\n" +
	"\x12CarePlanObjectives\x129\n" +
	"\x10short_term_goals\x18\x01 \x03(\v2\x0f.grpclient.GoalR\x0eshortTermGoals\x12;\n" +
	"\x11medium_term_goals\x18\x02 \x03(\v2\x0f.grpclient.GoalR\x0fmediumTermGoals\x127\n" +
	"\x0flong_term_goals\x18\x03 \x03(\v2\x0f.grpclient.GoalR\rlongTermGoals\"\x90\x01\n" +
	"\x04Goal\x12\x1c\n" +
	"\ttimeframe\x18\x01 \x01(\tR\ttimeframe\x12\x1d\n" +
	"\n" +
	"goal_title\x18\x02 \x01(\tR\tgoalTitle\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12)\n" +
	"\x10specific_actions\x18\x04 \x03(\tR\x0fspecificActions\"\x96\x01\n" +
	"\rInterventions\x12)\n" +
	"\x10daily_activities\x18\x01 \x03(\tR\x0fdailyActivities\x12+\n" +
	"\x11weekly_activities\x18\x02 \x03(\tR\x10weeklyActivities\x12-\n" +
	"\x12monthly_activities\x18\x03 \x03(\tR\x11monthlyActivities\"n\n" +
	"\rSuccessMetric\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12-\n" +
	"\x12measurement_method\x18\x03 \x01(\tR\x11measurementMethod\"@\n" +
	"\n" +
	"RiskFactor\x12\x12\n" +
	"\x04risk\x18\x01 \x01(\tR\x04risk\x12\x1e\n" +
	"\n" +
	"mitigation\x18\x02 \x01(\tR\n" +
	"mitigation\"I\n" +
	"\vSupportRole\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12&\n" +
	"\x0eresponsibility\x18\x02 \x01(\tR\x0eresponsibility\"v\n" +
	"\x0eReviewSchedule\x12\x14\n" +
	"\x05daily\x18\x01 \x01(\tR\x05daily\x12\x16\n" +
	"\x06weekly\x18\x02 \x01(\tR\x06weekly\x12\x18\n" +
	"\amonthly\x18\x03 \x01(\tR\amonthly\x12\x1c\n" +
	"\tquarterly\x18\x04 \x01(\tR\tquarterly\"W\n" +
	"\x12TransitionCriteria\x12\x1d\n" +
	"\n" +
	"next_level\x18\x01 \x01(\x05R\tnextLevel\x12\"\n" +
	"\frequirements\x18\x02 \x03(\tR\frequirements2r\n" +
	"\vCarePlanner\x12c\n" +
	"\x10GenerateCarePlan\x12&.grpclient.PersonalizedCarePlanRequest\x1a'.grpclient.PersonalizedCarePlanResponseB\x16Z\x14maicare_go/grpclientb\x06proto3"

var (
	file_proto_service_proto_rawDescOnce sync.Once
	file_proto_service_proto_rawDescData []byte
)

func file_proto_service_proto_rawDescGZIP() []byte {
	file_proto_service_proto_rawDescOnce.Do(func() {
		file_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)))
	})
	return file_proto_service_proto_rawDescData
}

var file_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_service_proto_goTypes = []any{
	(*PersonalizedCarePlanRequest)(nil),  // 0: grpclient.PersonalizedCarePlanRequest
	(*ClientData)(nil),                   // 1: grpclient.ClientData
	(*DomainLevels)(nil),                 // 2: grpclient.DomainLevels
	(*PersonalizedCarePlanResponse)(nil), // 3: grpclient.PersonalizedCarePlanResponse
	(*ClientProfile)(nil),                // 4: grpclient.ClientProfile
	(*CarePlanObjectives)(nil),           // 5: grpclient.CarePlanObjectives
	(*Goal)(nil),                         // 6: grpclient.Goal
	(*Interventions)(nil),                // 7: grpclient.Interventions
	(*SuccessMetric)(nil),                // 8: grpclient.SuccessMetric
	(*RiskFactor)(nil),                   // 9: grpclient.RiskFactor
	(*SupportRole)(nil),                  // 10: grpclient.SupportRole
	(*ReviewSchedule)(nil),               // 11: grpclient.ReviewSchedule
	(*TransitionCriteria)(nil),           // 12: grpclient.TransitionCriteria
	nil,                                  // 13: grpclient.PersonalizedCarePlanRequest.DomainDefinitionsEntry
	nil,                                  // 14: grpclient.DomainLevels.LevelsEntry
}
var file_proto_service_proto_depIdxs = []int32{
	1,  // 0: grpclient.PersonalizedCarePlanRequest.client_data:type_name -> grpclient.ClientData
	13, // 1: grpclient.PersonalizedCarePlanRequest.domain_definitions:type_name -> grpclient.PersonalizedCarePlanRequest.DomainDefinitionsEntry
	14, // 2: grpclient.DomainLevels.levels:type_name -> grpclient.DomainLevels.LevelsEntry
	4,  // 3: grpclient.PersonalizedCarePlanResponse.client_profile:type_name -> grpclient.ClientProfile
	5,  // 4: grpclient.PersonalizedCarePlanResponse.care_plan_objectives:type_name -> grpclient.CarePlanObjectives
	7,  // 5: grpclient.PersonalizedCarePlanResponse.interventions:type_name -> grpclient.Interventions
	8,  // 6: grpclient.PersonalizedCarePlanResponse.success_metrics:type_name -> grpclient.SuccessMetric
	9,  // 7: grpclient.PersonalizedCarePlanResponse.risk_factors:type_name -> grpclient.RiskFactor
	10, // 8: grpclient.PersonalizedCarePlanResponse.support_network:type_name -> grpclient.SupportRole
	11, // 9: grpclient.PersonalizedCarePlanResponse.review_schedule:type_name -> grpclient.ReviewSchedule
	12, // 10: grpclient.PersonalizedCarePlanResponse.transition_criteria:type_name -> grpclient.TransitionCriteria
	6,  // 11: grpclient.CarePlanObjectives.short_term_goals:type_name -> grpclient.Goal
	6,  // 12: grpclient.CarePlanObjectives.medium_term_goals:type_name -> grpclient.Goal
	6,  // 13: grpclient.CarePlanObjectives.long_term_goals:type_name -> grpclient.Goal
	2,  // 14: grpclient.PersonalizedCarePlanRequest.DomainDefinitionsEntry.value:type_name -> grpclient.DomainLevels
	0,  // 15: grpclient.CarePlanner.GenerateCarePlan:input_type -> grpclient.PersonalizedCarePlanRequest
	3,  // 16: grpclient.CarePlanner.GenerateCarePlan:output_type -> grpclient.PersonalizedCarePlanResponse
	16, // [16:17] is the sub-list for method output_type
	15, // [15:16] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_service_proto_init() }
func file_proto_service_proto_init() {
	if File_proto_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_proto_goTypes,
		DependencyIndexes: file_proto_service_proto_depIdxs,
		MessageInfos:      file_proto_service_proto_msgTypes,
	}.Build()
	File_proto_service_proto = out.File
	file_proto_service_proto_goTypes = nil
	file_proto_service_proto_depIdxs = nil
}
