// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addEventClientAttendee = `-- name: AddEventClientAttendee :exec
INSERT INTO calendar_event_attendees (event_id, client_id)
VALUES ($1, $2)
`

type AddEventClientAttendeeParams struct {
	EventID  uuid.UUID  `json:"event_id"`
	ClientID *uuid.UUID `json:"client_id"`
}

func (q *Queries) AddEventClientAttendee(ctx context.Context, arg AddEventClientAttendeeParams) error {
	_, err := q.db.Exec(ctx, addEventClientAttendee, arg.EventID, arg.ClientID)
	return err
}

const addEventClientAttendeesBatch = `-- name: AddEventClientAttendeesBatch :exec
INSERT INTO calendar_event_attendees (event_id, client_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT (event_id, client_id) WHERE client_id IS NOT NULL DO NOTHING
`

type AddEventClientAttendeesBatchParams struct {
	EventID   uuid.UUID   `json:"event_id"`
	ClientIds []uuid.UUID `json:"client_ids"`
}

func (q *Queries) AddEventClientAttendeesBatch(ctx context.Context, arg AddEventClientAttendeesBatchParams) error {
	_, err := q.db.Exec(ctx, addEventClientAttendeesBatch, arg.EventID, arg.ClientIds)
	return err
}

const addEventEmployeeAttendee = `-- name: AddEventEmployeeAttendee :exec
INSERT INTO calendar_event_attendees (event_id, employee_id)
VALUES ($1, $2)
`

type AddEventEmployeeAttendeeParams struct {
	EventID    uuid.UUID  `json:"event_id"`
	EmployeeID *uuid.UUID `json:"employee_id"`
}

func (q *Queries) AddEventEmployeeAttendee(ctx context.Context, arg AddEventEmployeeAttendeeParams) error {
	_, err := q.db.Exec(ctx, addEventEmployeeAttendee, arg.EventID, arg.EmployeeID)
	return err
}

const addEventEmployeeAttendeesBatch = `-- name: AddEventEmployeeAttendeesBatch :exec
INSERT INTO calendar_event_attendees (event_id, employee_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT (event_id, employee_id) WHERE employee_id IS NOT NULL DO NOTHING
`

type AddEventEmployeeAttendeesBatchParams struct {
	EventID     uuid.UUID   `json:"event_id"`
	EmployeeIds []uuid.UUID `json:"employee_ids"`
}

func (q *Queries) AddEventEmployeeAttendeesBatch(ctx context.Context, arg AddEventEmployeeAttendeesBatchParams) error {
	_, err := q.db.Exec(ctx, addEventEmployeeAttendeesBatch, arg.EventID, arg.EmployeeIds)
	return err
}

const addEventReminder = `-- name: AddEventReminder :one
INSERT INTO calendar_event_reminders (event_id, channel, minutes_before, remind_at)
VALUES ($1, 'in_app', $2, $3)
RETURNING id, minutes_before, remind_at
`

type AddEventReminderParams struct {
	EventID       uuid.UUID          `json:"event_id"`
	MinutesBefore *int32             `json:"minutes_before"`
	RemindAt      pgtype.Timestamptz `json:"remind_at"`
}

type AddEventReminderRow struct {
	ID            uuid.UUID          `json:"id"`
	MinutesBefore *int32             `json:"minutes_before"`
	RemindAt      pgtype.Timestamptz `json:"remind_at"`
}

func (q *Queries) AddEventReminder(ctx context.Context, arg AddEventReminderParams) (AddEventReminderRow, error) {
	row := q.db.QueryRow(ctx, addEventReminder, arg.EventID, arg.MinutesBefore, arg.RemindAt)
	var i AddEventReminderRow
	err := row.Scan(&i.ID, &i.MinutesBefore, &i.RemindAt)
	return i, err
}

const cancelCalendarEvent = `-- name: CancelCalendarEvent :exec
UPDATE calendar_events
SET status = 'cancelled', updated_at = now()
WHERE id = $1
`

func (q *Queries) CancelCalendarEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelCalendarEvent, id)
	return err
}

const createCalendarEvent = `-- name: CreateCalendarEvent :one
INSERT INTO calendar_events (
    organizer_employee_id,
    created_by_employee_id,
    kind,
    status,
    title,
    description,
    location,
    color,
    start_at,
    end_at,
    timezone,
    rrule,
    recurring_event_id,
    recurrence_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
RETURNING id, organizer_employee_id, created_by_employee_id, kind, status, work_approval_status, work_approved_by, work_approved_at, work_rejected_by, work_rejected_at, work_rejection_reason, title, description, location, color, start_at, end_at, timezone, rrule, recurring_event_id, recurrence_id, created_at, updated_at
`

type CreateCalendarEventParams struct {
	OrganizerEmployeeID uuid.UUID               `json:"organizer_employee_id"`
	CreatedByEmployeeID uuid.UUID               `json:"created_by_employee_id"`
	Kind                CalendarEventKindEnum   `json:"kind"`
	Status              CalendarEventStatusEnum `json:"status"`
	Title               string                  `json:"title"`
	Description         *string                 `json:"description"`
	Location            *string                 `json:"location"`
	Color               *string                 `json:"color"`
	StartAt             pgtype.Timestamptz      `json:"start_at"`
	EndAt               pgtype.Timestamptz      `json:"end_at"`
	Timezone            string                  `json:"timezone"`
	Rrule               *string                 `json:"rrule"`
	RecurringEventID    *uuid.UUID              `json:"recurring_event_id"`
	RecurrenceID        pgtype.Timestamptz      `json:"recurrence_id"`
}

func (q *Queries) CreateCalendarEvent(ctx context.Context, arg CreateCalendarEventParams) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, createCalendarEvent,
		arg.OrganizerEmployeeID,
		arg.CreatedByEmployeeID,
		arg.Kind,
		arg.Status,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.Color,
		arg.StartAt,
		arg.EndAt,
		arg.Timezone,
		arg.Rrule,
		arg.RecurringEventID,
		arg.RecurrenceID,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.OrganizerEmployeeID,
		&i.CreatedByEmployeeID,
		&i.Kind,
		&i.Status,
		&i.WorkApprovalStatus,
		&i.WorkApprovedBy,
		&i.WorkApprovedAt,
		&i.WorkRejectedBy,
		&i.WorkRejectedAt,
		&i.WorkRejectionReason,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Color,
		&i.StartAt,
		&i.EndAt,
		&i.Timezone,
		&i.Rrule,
		&i.RecurringEventID,
		&i.RecurrenceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAttendeesByEventID = `-- name: DeleteAttendeesByEventID :exec
DELETE FROM calendar_event_attendees
WHERE event_id = $1
`

func (q *Queries) DeleteAttendeesByEventID(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttendeesByEventID, eventID)
	return err
}

const deleteRemindersByEventID = `-- name: DeleteRemindersByEventID :exec
DELETE FROM calendar_event_reminders
WHERE event_id = $1
`

func (q *Queries) DeleteRemindersByEventID(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRemindersByEventID, eventID)
	return err
}

const getCalendarEventByID = `-- name: GetCalendarEventByID :one
SELECT id, organizer_employee_id, created_by_employee_id, kind, status, work_approval_status, work_approved_by, work_approved_at, work_rejected_by, work_rejected_at, work_rejection_reason, title, description, location, color, start_at, end_at, timezone, rrule, recurring_event_id, recurrence_id, created_at, updated_at
FROM calendar_events
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCalendarEventByID(ctx context.Context, id uuid.UUID) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, getCalendarEventByID, id)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.OrganizerEmployeeID,
		&i.CreatedByEmployeeID,
		&i.Kind,
		&i.Status,
		&i.WorkApprovalStatus,
		&i.WorkApprovedBy,
		&i.WorkApprovedAt,
		&i.WorkRejectedBy,
		&i.WorkRejectedAt,
		&i.WorkRejectionReason,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Color,
		&i.StartAt,
		&i.EndAt,
		&i.Timezone,
		&i.Rrule,
		&i.RecurringEventID,
		&i.RecurrenceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCalendarEventOverrideByMasterAndRecurrence = `-- name: GetCalendarEventOverrideByMasterAndRecurrence :one
SELECT id, organizer_employee_id, created_by_employee_id, kind, status, work_approval_status, work_approved_by, work_approved_at, work_rejected_by, work_rejected_at, work_rejection_reason, title, description, location, color, start_at, end_at, timezone, rrule, recurring_event_id, recurrence_id, created_at, updated_at
FROM calendar_events
WHERE recurring_event_id = $1
  AND recurrence_id = $2
LIMIT 1
`

type GetCalendarEventOverrideByMasterAndRecurrenceParams struct {
	MasterEventID *uuid.UUID         `json:"master_event_id"`
	RecurrenceID  pgtype.Timestamptz `json:"recurrence_id"`
}

func (q *Queries) GetCalendarEventOverrideByMasterAndRecurrence(ctx context.Context, arg GetCalendarEventOverrideByMasterAndRecurrenceParams) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, getCalendarEventOverrideByMasterAndRecurrence, arg.MasterEventID, arg.RecurrenceID)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.OrganizerEmployeeID,
		&i.CreatedByEmployeeID,
		&i.Kind,
		&i.Status,
		&i.WorkApprovalStatus,
		&i.WorkApprovedBy,
		&i.WorkApprovedAt,
		&i.WorkRejectedBy,
		&i.WorkRejectedAt,
		&i.WorkRejectionReason,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Color,
		&i.StartAt,
		&i.EndAt,
		&i.Timezone,
		&i.Rrule,
		&i.RecurringEventID,
		&i.RecurrenceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVisibleEventByID = `-- name: GetVisibleEventByID :one
SELECT ce.id, ce.organizer_employee_id, ce.created_by_employee_id, ce.kind, ce.status, ce.work_approval_status, ce.work_approved_by, ce.work_approved_at, ce.work_rejected_by, ce.work_rejected_at, ce.work_rejection_reason, ce.title, ce.description, ce.location, ce.color, ce.start_at, ce.end_at, ce.timezone, ce.rrule, ce.recurring_event_id, ce.recurrence_id, ce.created_at, ce.updated_at
FROM calendar_events ce
WHERE ce.id = $1
  AND (
      ce.organizer_employee_id = $2
      OR EXISTS (
          SELECT 1
          FROM calendar_event_attendees cea
          WHERE cea.event_id = ce.id
            AND cea.employee_id = $2
      )
  )
LIMIT 1
`

type GetVisibleEventByIDParams struct {
	ID         uuid.UUID `json:"id"`
	EmployeeID uuid.UUID `json:"employee_id"`
}

func (q *Queries) GetVisibleEventByID(ctx context.Context, arg GetVisibleEventByIDParams) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, getVisibleEventByID, arg.ID, arg.EmployeeID)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.OrganizerEmployeeID,
		&i.CreatedByEmployeeID,
		&i.Kind,
		&i.Status,
		&i.WorkApprovalStatus,
		&i.WorkApprovedBy,
		&i.WorkApprovedAt,
		&i.WorkRejectedBy,
		&i.WorkRejectedAt,
		&i.WorkRejectionReason,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Color,
		&i.StartAt,
		&i.EndAt,
		&i.Timezone,
		&i.Rrule,
		&i.RecurringEventID,
		&i.RecurrenceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAttendeesByEventIDs = `-- name: ListAttendeesByEventIDs :many
SELECT event_id, employee_id, client_id
FROM calendar_event_attendees
WHERE event_id = ANY($1::uuid[])
`

type ListAttendeesByEventIDsRow struct {
	EventID    uuid.UUID  `json:"event_id"`
	EmployeeID *uuid.UUID `json:"employee_id"`
	ClientID   *uuid.UUID `json:"client_id"`
}

func (q *Queries) ListAttendeesByEventIDs(ctx context.Context, eventIds []uuid.UUID) ([]ListAttendeesByEventIDsRow, error) {
	rows, err := q.db.Query(ctx, listAttendeesByEventIDs, eventIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttendeesByEventIDsRow{}
	for rows.Next() {
		var i ListAttendeesByEventIDsRow
		if err := rows.Scan(&i.EventID, &i.EmployeeID, &i.ClientID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientAppointmentsInRange = `-- name: ListClientAppointmentsInRange :many
SELECT
    ce.id AS appointment_id,
    ce.start_at AS start_time,
    ce.end_at AS end_time,
    ce.location,
    ce.description,
    ce.color,
    ce.status,
    ce.organizer_employee_id AS creator_employee_id,
    ce.created_at
FROM
    calendar_events ce
JOIN
    calendar_event_attendees cea ON ce.id = cea.event_id
WHERE
    ce.kind = 'appointment'
    AND ce.status <> 'cancelled'
    AND cea.client_id = $1
    AND ce.start_at < $2
    AND ce.end_at > $3
ORDER BY
    ce.start_at
`

type ListClientAppointmentsInRangeParams struct {
	ClientID  *uuid.UUID         `json:"client_id"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
	StartDate pgtype.Timestamptz `json:"start_date"`
}

type ListClientAppointmentsInRangeRow struct {
	AppointmentID     uuid.UUID               `json:"appointment_id"`
	StartTime         pgtype.Timestamptz      `json:"start_time"`
	EndTime           pgtype.Timestamptz      `json:"end_time"`
	Location          *string                 `json:"location"`
	Description       *string                 `json:"description"`
	Color             *string                 `json:"color"`
	Status            CalendarEventStatusEnum `json:"status"`
	CreatorEmployeeID uuid.UUID               `json:"creator_employee_id"`
	CreatedAt         pgtype.Timestamptz      `json:"created_at"`
}

func (q *Queries) ListClientAppointmentsInRange(ctx context.Context, arg ListClientAppointmentsInRangeParams) ([]ListClientAppointmentsInRangeRow, error) {
	rows, err := q.db.Query(ctx, listClientAppointmentsInRange, arg.ClientID, arg.EndDate, arg.StartDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientAppointmentsInRangeRow{}
	for rows.Next() {
		var i ListClientAppointmentsInRangeRow
		if err := rows.Scan(
			&i.AppointmentID,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.Description,
			&i.Color,
			&i.Status,
			&i.CreatorEmployeeID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientAppointmentsStartingInRange = `-- name: ListClientAppointmentsStartingInRange :many
SELECT
    ce.id AS appointment_id,
    ce.start_at AS start_time,
    ce.end_at AS end_time,
    ce.location,
    ce.description,
    ce.color,
    ce.status,
    ce.organizer_employee_id AS creator_employee_id,
    ce.created_at
FROM
    calendar_events ce
JOIN
    calendar_event_attendees cea ON ce.id = cea.event_id
WHERE
    ce.kind = 'appointment'
    AND ce.status <> 'cancelled'
    AND cea.client_id = $1
    AND ce.start_at >= $2
    AND ce.start_at < $3
ORDER BY
    ce.start_at
`

type ListClientAppointmentsStartingInRangeParams struct {
	ClientID  *uuid.UUID         `json:"client_id"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
}

type ListClientAppointmentsStartingInRangeRow struct {
	AppointmentID     uuid.UUID               `json:"appointment_id"`
	StartTime         pgtype.Timestamptz      `json:"start_time"`
	EndTime           pgtype.Timestamptz      `json:"end_time"`
	Location          *string                 `json:"location"`
	Description       *string                 `json:"description"`
	Color             *string                 `json:"color"`
	Status            CalendarEventStatusEnum `json:"status"`
	CreatorEmployeeID uuid.UUID               `json:"creator_employee_id"`
	CreatedAt         pgtype.Timestamptz      `json:"created_at"`
}

func (q *Queries) ListClientAppointmentsStartingInRange(ctx context.Context, arg ListClientAppointmentsStartingInRangeParams) ([]ListClientAppointmentsStartingInRangeRow, error) {
	rows, err := q.db.Query(ctx, listClientAppointmentsStartingInRange, arg.ClientID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientAppointmentsStartingInRangeRow{}
	for rows.Next() {
		var i ListClientAppointmentsStartingInRangeRow
		if err := rows.Scan(
			&i.AppointmentID,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.Description,
			&i.Color,
			&i.Status,
			&i.CreatorEmployeeID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeAppointmentsInRange = `-- name: ListEmployeeAppointmentsInRange :many
SELECT
    ce.id AS appointment_id,
    ce.start_at AS start_time,
    ce.end_at AS end_time,
    ce.location,
    ce.description,
    ce.color,
    ce.status,
    (ce.work_approval_status = 'approved') AS is_confirmed,
    ce.organizer_employee_id AS creator_employee_id,
    ce.created_at,
    CASE
        WHEN ce.organizer_employee_id = $1 THEN 'CREATOR'
        ELSE 'PARTICIPANT'
    END AS involvement_type
FROM
    calendar_events ce
LEFT JOIN
    calendar_event_attendees cea ON ce.id = cea.event_id
WHERE
    ce.kind = 'appointment'
    AND ce.status <> 'cancelled'
    AND (ce.organizer_employee_id = $1 OR cea.employee_id = $1)
    AND ce.start_at < $2
    AND ce.end_at > $3
ORDER BY
    ce.start_at
`

type ListEmployeeAppointmentsInRangeParams struct {
	EmployeeID uuid.UUID          `json:"employee_id"`
	EndDate    pgtype.Timestamptz `json:"end_date"`
	StartDate  pgtype.Timestamptz `json:"start_date"`
}

type ListEmployeeAppointmentsInRangeRow struct {
	AppointmentID     uuid.UUID               `json:"appointment_id"`
	StartTime         pgtype.Timestamptz      `json:"start_time"`
	EndTime           pgtype.Timestamptz      `json:"end_time"`
	Location          *string                 `json:"location"`
	Description       *string                 `json:"description"`
	Color             *string                 `json:"color"`
	Status            CalendarEventStatusEnum `json:"status"`
	IsConfirmed       bool                    `json:"is_confirmed"`
	CreatorEmployeeID uuid.UUID               `json:"creator_employee_id"`
	CreatedAt         pgtype.Timestamptz      `json:"created_at"`
	InvolvementType   string                  `json:"involvement_type"`
}

func (q *Queries) ListEmployeeAppointmentsInRange(ctx context.Context, arg ListEmployeeAppointmentsInRangeParams) ([]ListEmployeeAppointmentsInRangeRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeAppointmentsInRange, arg.EmployeeID, arg.EndDate, arg.StartDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeAppointmentsInRangeRow{}
	for rows.Next() {
		var i ListEmployeeAppointmentsInRangeRow
		if err := rows.Scan(
			&i.AppointmentID,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.Description,
			&i.Color,
			&i.Status,
			&i.IsConfirmed,
			&i.CreatorEmployeeID,
			&i.CreatedAt,
			&i.InvolvementType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemindersByEventID = `-- name: ListRemindersByEventID :many
SELECT id, minutes_before, remind_at
FROM calendar_event_reminders
WHERE event_id = $1
ORDER BY created_at ASC
`

type ListRemindersByEventIDRow struct {
	ID            uuid.UUID          `json:"id"`
	MinutesBefore *int32             `json:"minutes_before"`
	RemindAt      pgtype.Timestamptz `json:"remind_at"`
}

func (q *Queries) ListRemindersByEventID(ctx context.Context, eventID uuid.UUID) ([]ListRemindersByEventIDRow, error) {
	rows, err := q.db.Query(ctx, listRemindersByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRemindersByEventIDRow{}
	for rows.Next() {
		var i ListRemindersByEventIDRow
		if err := rows.Scan(&i.ID, &i.MinutesBefore, &i.RemindAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesExceptions = `-- name: ListSeriesExceptions :many
SELECT id, organizer_employee_id, created_by_employee_id, kind, status, work_approval_status, work_approved_by, work_approved_at, work_rejected_by, work_rejected_at, work_rejection_reason, title, description, location, color, start_at, end_at, timezone, rrule, recurring_event_id, recurrence_id, created_at, updated_at
FROM calendar_events
WHERE recurring_event_id = ANY($1::uuid[])
`

func (q *Queries) ListSeriesExceptions(ctx context.Context, seriesIds []uuid.UUID) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, listSeriesExceptions, seriesIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerEmployeeID,
			&i.CreatedByEmployeeID,
			&i.Kind,
			&i.Status,
			&i.WorkApprovalStatus,
			&i.WorkApprovedBy,
			&i.WorkApprovedAt,
			&i.WorkRejectedBy,
			&i.WorkRejectedAt,
			&i.WorkRejectionReason,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.Color,
			&i.StartAt,
			&i.EndAt,
			&i.Timezone,
			&i.Rrule,
			&i.RecurringEventID,
			&i.RecurrenceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesExceptionsStartingInRange = `-- name: ListSeriesExceptionsStartingInRange :many
SELECT id, organizer_employee_id, created_by_employee_id, kind, status, work_approval_status, work_approved_by, work_approved_at, work_rejected_by, work_rejected_at, work_rejection_reason, title, description, location, color, start_at, end_at, timezone, rrule, recurring_event_id, recurrence_id, created_at, updated_at
FROM calendar_events
WHERE recurring_event_id = ANY($1::uuid[])
  AND kind = 'appointment'
  AND start_at >= $2
  AND start_at < $3
  AND (
      COALESCE(array_length($4::uuid[], 1), 0) = 0
      OR organizer_employee_id = ANY($4::uuid[])
      OR EXISTS (
          SELECT 1
          FROM calendar_event_attendees cea
          WHERE cea.event_id = calendar_events.id
            AND cea.employee_id = ANY($4::uuid[])
      )
  )
`

type ListSeriesExceptionsStartingInRangeParams struct {
	SeriesIds   []uuid.UUID        `json:"series_ids"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	EmployeeIds []uuid.UUID        `json:"employee_ids"`
}

func (q *Queries) ListSeriesExceptionsStartingInRange(ctx context.Context, arg ListSeriesExceptionsStartingInRangeParams) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, listSeriesExceptionsStartingInRange,
		arg.SeriesIds,
		arg.StartAt,
		arg.EndAt,
		arg.EmployeeIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerEmployeeID,
			&i.CreatedByEmployeeID,
			&i.Kind,
			&i.Status,
			&i.WorkApprovalStatus,
			&i.WorkApprovedBy,
			&i.WorkApprovedAt,
			&i.WorkRejectedBy,
			&i.WorkRejectedAt,
			&i.WorkRejectionReason,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.Color,
			&i.StartAt,
			&i.EndAt,
			&i.Timezone,
			&i.Rrule,
			&i.RecurringEventID,
			&i.RecurrenceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnbilledClientAppointmentsStartingInRange = `-- name: ListUnbilledClientAppointmentsStartingInRange :many

SELECT
    ce.id AS appointment_id,
    ce.start_at AS start_time,
    ce.end_at AS end_time,
    ce.timezone,
    ce.status,
    ce.organizer_employee_id AS creator_employee_id,
    ce.created_at
FROM calendar_events ce
JOIN calendar_event_attendees cea ON ce.id = cea.event_id
LEFT JOIN billed_calendar_event bce
    ON bce.calendar_event_id = ce.id
   AND bce.client_id = cea.client_id
   AND bce.voided_at IS NULL
WHERE ce.kind = 'appointment'
  AND ce.status <> 'cancelled'
  AND ce.work_approval_status = 'approved'
  AND cea.client_id = $1
  AND ce.start_at >= $2
  AND ce.start_at < $3
  AND bce.id IS NULL
ORDER BY ce.start_at
`

type ListUnbilledClientAppointmentsStartingInRangeParams struct {
	ClientID  *uuid.UUID         `json:"client_id"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
}

type ListUnbilledClientAppointmentsStartingInRangeRow struct {
	AppointmentID     uuid.UUID               `json:"appointment_id"`
	StartTime         pgtype.Timestamptz      `json:"start_time"`
	EndTime           pgtype.Timestamptz      `json:"end_time"`
	Timezone          string                  `json:"timezone"`
	Status            CalendarEventStatusEnum `json:"status"`
	CreatorEmployeeID uuid.UUID               `json:"creator_employee_id"`
	CreatedAt         pgtype.Timestamptz      `json:"created_at"`
}

// ==========================================
// Invoicing Helpers
// ==========================================
// Returns appointments for a client that start within [start_date, end_date) and are not already billed (unless voided).
func (q *Queries) ListUnbilledClientAppointmentsStartingInRange(ctx context.Context, arg ListUnbilledClientAppointmentsStartingInRangeParams) ([]ListUnbilledClientAppointmentsStartingInRangeRow, error) {
	rows, err := q.db.Query(ctx, listUnbilledClientAppointmentsStartingInRange, arg.ClientID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnbilledClientAppointmentsStartingInRangeRow{}
	for rows.Next() {
		var i ListUnbilledClientAppointmentsStartingInRangeRow
		if err := rows.Scan(
			&i.AppointmentID,
			&i.StartTime,
			&i.EndTime,
			&i.Timezone,
			&i.Status,
			&i.CreatorEmployeeID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleMasterEvents = `-- name: ListVisibleMasterEvents :many
SELECT ce.id, ce.organizer_employee_id, ce.created_by_employee_id, ce.kind, ce.status, ce.work_approval_status, ce.work_approved_by, ce.work_approved_at, ce.work_rejected_by, ce.work_rejected_at, ce.work_rejection_reason, ce.title, ce.description, ce.location, ce.color, ce.start_at, ce.end_at, ce.timezone, ce.rrule, ce.recurring_event_id, ce.recurrence_id, ce.created_at, ce.updated_at
FROM calendar_events ce
WHERE ce.recurring_event_id IS NULL
  AND ce.status <> 'cancelled'
  AND (
      ce.organizer_employee_id = $1
      OR EXISTS (
          SELECT 1
          FROM calendar_event_attendees cea
          WHERE cea.event_id = ce.id
            AND cea.employee_id = $1
      )
  )
  AND (
      (ce.rrule IS NULL AND ce.start_at < $2 AND ce.end_at > $3)
      OR
      (ce.rrule IS NOT NULL AND ce.start_at < $2)
  )
`

type ListVisibleMasterEventsParams struct {
	EmployeeID uuid.UUID          `json:"employee_id"`
	EndAt      pgtype.Timestamptz `json:"end_at"`
	StartAt    pgtype.Timestamptz `json:"start_at"`
}

func (q *Queries) ListVisibleMasterEvents(ctx context.Context, arg ListVisibleMasterEventsParams) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, listVisibleMasterEvents, arg.EmployeeID, arg.EndAt, arg.StartAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerEmployeeID,
			&i.CreatedByEmployeeID,
			&i.Kind,
			&i.Status,
			&i.WorkApprovalStatus,
			&i.WorkApprovedBy,
			&i.WorkApprovedAt,
			&i.WorkRejectedBy,
			&i.WorkRejectedAt,
			&i.WorkRejectionReason,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.Color,
			&i.StartAt,
			&i.EndAt,
			&i.Timezone,
			&i.Rrule,
			&i.RecurringEventID,
			&i.RecurrenceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkApprovalQueueOneOffAppointmentsStartingInRange = `-- name: ListWorkApprovalQueueOneOffAppointmentsStartingInRange :many

SELECT ce.id, ce.organizer_employee_id, ce.created_by_employee_id, ce.kind, ce.status, ce.work_approval_status, ce.work_approved_by, ce.work_approved_at, ce.work_rejected_by, ce.work_rejected_at, ce.work_rejection_reason, ce.title, ce.description, ce.location, ce.color, ce.start_at, ce.end_at, ce.timezone, ce.rrule, ce.recurring_event_id, ce.recurrence_id, ce.created_at, ce.updated_at
FROM calendar_events ce
WHERE ce.kind = 'appointment'
  AND ce.status <> 'cancelled'
  AND ce.recurring_event_id IS NULL
  AND ce.rrule IS NULL
  AND ce.start_at >= $1
  AND ce.start_at < $2
  AND EXISTS (
      SELECT 1
      FROM calendar_event_attendees cea
      WHERE cea.event_id = ce.id
        AND cea.client_id IS NOT NULL
  )
  AND (
      COALESCE(array_length($3::uuid[], 1), 0) = 0
      OR ce.organizer_employee_id = ANY($3::uuid[])
      OR EXISTS (
          SELECT 1
          FROM calendar_event_attendees cea
          WHERE cea.event_id = ce.id
            AND cea.employee_id = ANY($3::uuid[])
      )
  )
ORDER BY ce.start_at DESC
`

type ListWorkApprovalQueueOneOffAppointmentsStartingInRangeParams struct {
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	EmployeeIds []uuid.UUID        `json:"employee_ids"`
}

// ==========================================
// Work Approval Queue (Admin)
// ==========================================
func (q *Queries) ListWorkApprovalQueueOneOffAppointmentsStartingInRange(ctx context.Context, arg ListWorkApprovalQueueOneOffAppointmentsStartingInRangeParams) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, listWorkApprovalQueueOneOffAppointmentsStartingInRange, arg.StartAt, arg.EndAt, arg.EmployeeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerEmployeeID,
			&i.CreatedByEmployeeID,
			&i.Kind,
			&i.Status,
			&i.WorkApprovalStatus,
			&i.WorkApprovedBy,
			&i.WorkApprovedAt,
			&i.WorkRejectedBy,
			&i.WorkRejectedAt,
			&i.WorkRejectionReason,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.Color,
			&i.StartAt,
			&i.EndAt,
			&i.Timezone,
			&i.Rrule,
			&i.RecurringEventID,
			&i.RecurrenceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkApprovalQueueRecurringMastersStartingBeforeEnd = `-- name: ListWorkApprovalQueueRecurringMastersStartingBeforeEnd :many
SELECT ce.id, ce.organizer_employee_id, ce.created_by_employee_id, ce.kind, ce.status, ce.work_approval_status, ce.work_approved_by, ce.work_approved_at, ce.work_rejected_by, ce.work_rejected_at, ce.work_rejection_reason, ce.title, ce.description, ce.location, ce.color, ce.start_at, ce.end_at, ce.timezone, ce.rrule, ce.recurring_event_id, ce.recurrence_id, ce.created_at, ce.updated_at
FROM calendar_events ce
WHERE ce.kind = 'appointment'
  AND ce.status <> 'cancelled'
  AND ce.recurring_event_id IS NULL
  AND ce.rrule IS NOT NULL
  AND ce.start_at < $1
  AND EXISTS (
      SELECT 1
      FROM calendar_event_attendees cea
      WHERE cea.event_id = ce.id
        AND cea.client_id IS NOT NULL
  )
  AND (
      COALESCE(array_length($2::uuid[], 1), 0) = 0
      OR ce.organizer_employee_id = ANY($2::uuid[])
      OR EXISTS (
          SELECT 1
          FROM calendar_event_attendees cea
          WHERE cea.event_id = ce.id
            AND cea.employee_id = ANY($2::uuid[])
      )
  )
ORDER BY ce.start_at DESC
`

type ListWorkApprovalQueueRecurringMastersStartingBeforeEndParams struct {
	EndAt       pgtype.Timestamptz `json:"end_at"`
	EmployeeIds []uuid.UUID        `json:"employee_ids"`
}

func (q *Queries) ListWorkApprovalQueueRecurringMastersStartingBeforeEnd(ctx context.Context, arg ListWorkApprovalQueueRecurringMastersStartingBeforeEndParams) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, listWorkApprovalQueueRecurringMastersStartingBeforeEnd, arg.EndAt, arg.EmployeeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerEmployeeID,
			&i.CreatedByEmployeeID,
			&i.Kind,
			&i.Status,
			&i.WorkApprovalStatus,
			&i.WorkApprovedBy,
			&i.WorkApprovedAt,
			&i.WorkRejectedBy,
			&i.WorkRejectedAt,
			&i.WorkRejectionReason,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.Color,
			&i.StartAt,
			&i.EndAt,
			&i.Timezone,
			&i.Rrule,
			&i.RecurringEventID,
			&i.RecurrenceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCalendarEvent = `-- name: UpdateCalendarEvent :one
UPDATE calendar_events
SET
    title = COALESCE($1, title),
    description = COALESCE($2, description),
    location = COALESCE($3, location),
    color = COALESCE($4, color),
    start_at = COALESCE($5, start_at),
    end_at = COALESCE($6, end_at),
    rrule = CASE
        WHEN $7::TEXT IS NOT NULL THEN $7
        ELSE rrule
    END,
    updated_at = now()
WHERE id = $8
RETURNING id, organizer_employee_id, created_by_employee_id, kind, status, work_approval_status, work_approved_by, work_approved_at, work_rejected_by, work_rejected_at, work_rejection_reason, title, description, location, color, start_at, end_at, timezone, rrule, recurring_event_id, recurrence_id, created_at, updated_at
`

type UpdateCalendarEventParams struct {
	Title       *string            `json:"title"`
	Description *string            `json:"description"`
	Location    *string            `json:"location"`
	Color       *string            `json:"color"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	Rrule       *string            `json:"rrule"`
	ID          uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateCalendarEvent(ctx context.Context, arg UpdateCalendarEventParams) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, updateCalendarEvent,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.Color,
		arg.StartAt,
		arg.EndAt,
		arg.Rrule,
		arg.ID,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.OrganizerEmployeeID,
		&i.CreatedByEmployeeID,
		&i.Kind,
		&i.Status,
		&i.WorkApprovalStatus,
		&i.WorkApprovedBy,
		&i.WorkApprovedAt,
		&i.WorkRejectedBy,
		&i.WorkRejectedAt,
		&i.WorkRejectionReason,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Color,
		&i.StartAt,
		&i.EndAt,
		&i.Timezone,
		&i.Rrule,
		&i.RecurringEventID,
		&i.RecurrenceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCalendarEventRRule = `-- name: UpdateCalendarEventRRule :exec
UPDATE calendar_events
SET rrule = $1, updated_at = now()
WHERE id = $2
`

type UpdateCalendarEventRRuleParams struct {
	Rrule *string   `json:"rrule"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) UpdateCalendarEventRRule(ctx context.Context, arg UpdateCalendarEventRRuleParams) error {
	_, err := q.db.Exec(ctx, updateCalendarEventRRule, arg.Rrule, arg.ID)
	return err
}

const updateCalendarEventWorkApproval = `-- name: UpdateCalendarEventWorkApproval :exec
UPDATE calendar_events
SET
    work_approval_status = $1,
    work_approved_by = CASE WHEN $1 = 'approved' THEN $2::uuid ELSE NULL END,
    work_approved_at = CASE WHEN $1 = 'approved' THEN CURRENT_TIMESTAMP ELSE NULL END,
    work_rejected_by = CASE WHEN $1 = 'rejected' THEN $2::uuid ELSE NULL END,
    work_rejected_at = CASE WHEN $1 = 'rejected' THEN CURRENT_TIMESTAMP ELSE NULL END,
    work_rejection_reason = CASE WHEN $1 = 'rejected' THEN $3::text ELSE NULL END,
    updated_at = now()
WHERE id = $4
`

type UpdateCalendarEventWorkApprovalParams struct {
	WorkApprovalStatus CalendarEventWorkApprovalStatusEnum `json:"work_approval_status"`
	ActorUserID        uuid.UUID                           `json:"actor_user_id"`
	RejectionReason    *string                             `json:"rejection_reason"`
	EventID            uuid.UUID                           `json:"event_id"`
}

func (q *Queries) UpdateCalendarEventWorkApproval(ctx context.Context, arg UpdateCalendarEventWorkApprovalParams) error {
	_, err := q.db.Exec(ctx, updateCalendarEventWorkApproval,
		arg.WorkApprovalStatus,
		arg.ActorUserID,
		arg.RejectionReason,
		arg.EventID,
	)
	return err
}

const upsertCalendarEventOverride = `-- name: UpsertCalendarEventOverride :one
INSERT INTO calendar_events (
    organizer_employee_id,
    created_by_employee_id,
    kind,
    status,
    title,
    description,
    location,
    color,
    start_at,
    end_at,
    timezone,
    recurring_event_id,
    recurrence_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
ON CONFLICT (recurring_event_id, recurrence_id)
DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    location = EXCLUDED.location,
    color = EXCLUDED.color,
    start_at = EXCLUDED.start_at,
    end_at = EXCLUDED.end_at,
    status = EXCLUDED.status,
    updated_at = now()
RETURNING id, organizer_employee_id, created_by_employee_id, kind, status, work_approval_status, work_approved_by, work_approved_at, work_rejected_by, work_rejected_at, work_rejection_reason, title, description, location, color, start_at, end_at, timezone, rrule, recurring_event_id, recurrence_id, created_at, updated_at
`

type UpsertCalendarEventOverrideParams struct {
	OrganizerEmployeeID uuid.UUID               `json:"organizer_employee_id"`
	CreatedByEmployeeID uuid.UUID               `json:"created_by_employee_id"`
	Kind                CalendarEventKindEnum   `json:"kind"`
	Status              CalendarEventStatusEnum `json:"status"`
	Title               string                  `json:"title"`
	Description         *string                 `json:"description"`
	Location            *string                 `json:"location"`
	Color               *string                 `json:"color"`
	StartAt             pgtype.Timestamptz      `json:"start_at"`
	EndAt               pgtype.Timestamptz      `json:"end_at"`
	Timezone            string                  `json:"timezone"`
	RecurringEventID    *uuid.UUID              `json:"recurring_event_id"`
	RecurrenceID        pgtype.Timestamptz      `json:"recurrence_id"`
}

func (q *Queries) UpsertCalendarEventOverride(ctx context.Context, arg UpsertCalendarEventOverrideParams) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, upsertCalendarEventOverride,
		arg.OrganizerEmployeeID,
		arg.CreatedByEmployeeID,
		arg.Kind,
		arg.Status,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.Color,
		arg.StartAt,
		arg.EndAt,
		arg.Timezone,
		arg.RecurringEventID,
		arg.RecurrenceID,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.OrganizerEmployeeID,
		&i.CreatedByEmployeeID,
		&i.Kind,
		&i.Status,
		&i.WorkApprovalStatus,
		&i.WorkApprovedBy,
		&i.WorkApprovedAt,
		&i.WorkRejectedBy,
		&i.WorkRejectedAt,
		&i.WorkRejectionReason,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Color,
		&i.StartAt,
		&i.EndAt,
		&i.Timezone,
		&i.Rrule,
		&i.RecurringEventID,
		&i.RecurrenceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
