// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client_progress_report.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAiGeneratedReport = `-- name: CreateAiGeneratedReport :one
INSERT INTO ai_generated_reports (
        client_id,
        report_text,
        start_date,
        end_date

    ) VALUES (
        $1, $2, $3, $4
    ) RETURNING id, report_text, client_id, start_date, end_date, created_at
`

type CreateAiGeneratedReportParams struct {
	ClientID   uuid.UUID   `json:"client_id"`
	ReportText string      `json:"report_text"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
}

func (q *Queries) CreateAiGeneratedReport(ctx context.Context, arg CreateAiGeneratedReportParams) (AiGeneratedReport, error) {
	row := q.db.QueryRow(ctx, createAiGeneratedReport,
		arg.ClientID,
		arg.ReportText,
		arg.StartDate,
		arg.EndDate,
	)
	var i AiGeneratedReport
	err := row.Scan(
		&i.ID,
		&i.ReportText,
		&i.ClientID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const createProgressReport = `-- name: CreateProgressReport :one
INSERT INTO progress_report (
        client_id,
        employee_id,
        title,
        date,
        report_text,
        type,
        emotional_state
    ) VALUES (
        $1, $2, $3, $4, $5, $6, $7
    ) RETURNING id, client_id, date, title, report_text, employee_id, type, emotional_state, created_at
`

type CreateProgressReportParams struct {
	ClientID       uuid.UUID              `json:"client_id"`
	EmployeeID     *uuid.UUID             `json:"employee_id"`
	Title          *string                `json:"title"`
	Date           pgtype.Timestamptz     `json:"date"`
	ReportText     string                 `json:"report_text"`
	Type           ProgressReportTypeEnum `json:"type"`
	EmotionalState EmotionalStateEnum     `json:"emotional_state"`
}

func (q *Queries) CreateProgressReport(ctx context.Context, arg CreateProgressReportParams) (ProgressReport, error) {
	row := q.db.QueryRow(ctx, createProgressReport,
		arg.ClientID,
		arg.EmployeeID,
		arg.Title,
		arg.Date,
		arg.ReportText,
		arg.Type,
		arg.EmotionalState,
	)
	var i ProgressReport
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Date,
		&i.Title,
		&i.ReportText,
		&i.EmployeeID,
		&i.Type,
		&i.EmotionalState,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProgressReport = `-- name: DeleteProgressReport :exec
DELETE FROM progress_report
WHERE id = $1
`

func (q *Queries) DeleteProgressReport(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProgressReport, id)
	return err
}

const getAiGeneratedReport = `-- name: GetAiGeneratedReport :one
SELECT 
    agr.id, agr.report_text, agr.client_id, agr.start_date, agr.end_date, agr.created_at
FROM ai_generated_reports agr
WHERE agr.id = $1 LIMIT 1
`

func (q *Queries) GetAiGeneratedReport(ctx context.Context, id uuid.UUID) (AiGeneratedReport, error) {
	row := q.db.QueryRow(ctx, getAiGeneratedReport, id)
	var i AiGeneratedReport
	err := row.Scan(
		&i.ID,
		&i.ReportText,
		&i.ClientID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const getProgressReport = `-- name: GetProgressReport :one
SELECT 
    pr.id, pr.client_id, pr.date, pr.title, pr.report_text, pr.employee_id, pr.type, pr.emotional_state, pr.created_at,
    COALESCE(e.first_name, '') AS employee_first_name,
    COALESCE(e.last_name, '') AS employee_last_name,
    u.profile_picture AS employee_profile_picture
FROM progress_report pr
LEFT JOIN employee_profile e ON pr.employee_id = e.id
LEFT JOIN custom_User u ON e.user_id = u.id
WHERE pr.id = $1 LIMIT 1
`

type GetProgressReportRow struct {
	ID                     uuid.UUID              `json:"id"`
	ClientID               uuid.UUID              `json:"client_id"`
	Date                   pgtype.Timestamptz     `json:"date"`
	Title                  *string                `json:"title"`
	ReportText             string                 `json:"report_text"`
	EmployeeID             *uuid.UUID             `json:"employee_id"`
	Type                   ProgressReportTypeEnum `json:"type"`
	EmotionalState         EmotionalStateEnum     `json:"emotional_state"`
	CreatedAt              pgtype.Timestamptz     `json:"created_at"`
	EmployeeFirstName      string                 `json:"employee_first_name"`
	EmployeeLastName       string                 `json:"employee_last_name"`
	EmployeeProfilePicture *string                `json:"employee_profile_picture"`
}

func (q *Queries) GetProgressReport(ctx context.Context, id uuid.UUID) (GetProgressReportRow, error) {
	row := q.db.QueryRow(ctx, getProgressReport, id)
	var i GetProgressReportRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Date,
		&i.Title,
		&i.ReportText,
		&i.EmployeeID,
		&i.Type,
		&i.EmotionalState,
		&i.CreatedAt,
		&i.EmployeeFirstName,
		&i.EmployeeLastName,
		&i.EmployeeProfilePicture,
	)
	return i, err
}

const getProgressReportsByDateRange = `-- name: GetProgressReportsByDateRange :many
SELECT id, client_id, date, title, report_text, employee_id, type, emotional_state, created_at
FROM progress_report
WHERE client_id = $1
  AND date >= $2
  AND date <= $3
ORDER BY date ASC
`

type GetProgressReportsByDateRangeParams struct {
	ClientID  uuid.UUID          `json:"client_id"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
}

func (q *Queries) GetProgressReportsByDateRange(ctx context.Context, arg GetProgressReportsByDateRangeParams) ([]ProgressReport, error) {
	rows, err := q.db.Query(ctx, getProgressReportsByDateRange, arg.ClientID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProgressReport{}
	for rows.Next() {
		var i ProgressReport
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Date,
			&i.Title,
			&i.ReportText,
			&i.EmployeeID,
			&i.Type,
			&i.EmotionalState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAiGeneratedReports = `-- name: ListAiGeneratedReports :many
SELECT 
    agr.id, agr.report_text, agr.client_id, agr.start_date, agr.end_date, agr.created_at,
    COUNT(*) OVER() AS total_count
FROM ai_generated_reports agr
WHERE agr.client_id = $1
ORDER BY agr.created_at DESC
LIMIT $2 OFFSET $3
`

type ListAiGeneratedReportsParams struct {
	ClientID uuid.UUID `json:"client_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListAiGeneratedReportsRow struct {
	ID         uuid.UUID          `json:"id"`
	ReportText string             `json:"report_text"`
	ClientID   uuid.UUID          `json:"client_id"`
	StartDate  pgtype.Date        `json:"start_date"`
	EndDate    pgtype.Date        `json:"end_date"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	TotalCount int64              `json:"total_count"`
}

func (q *Queries) ListAiGeneratedReports(ctx context.Context, arg ListAiGeneratedReportsParams) ([]ListAiGeneratedReportsRow, error) {
	rows, err := q.db.Query(ctx, listAiGeneratedReports, arg.ClientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAiGeneratedReportsRow{}
	for rows.Next() {
		var i ListAiGeneratedReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReportText,
			&i.ClientID,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgressReports = `-- name: ListProgressReports :many
SELECT 
    pr.id, pr.client_id, pr.date, pr.title, pr.report_text, pr.employee_id, pr.type, pr.emotional_state, pr.created_at,
    COUNT(*) OVER() AS total_count,
    COALESCE(e.first_name, '') AS employee_first_name,
    COALESCE(e.last_name, '') AS employee_last_name,
    u.profile_picture AS employee_profile_picture
FROM progress_report pr
LEFT JOIN employee_profile e ON pr.employee_id = e.id
LEFT JOIN custom_User u ON e.user_id = u.id
WHERE pr.client_id = $1
  AND (
    $2::progress_report_type_enum IS NULL
    OR pr.type = $2::progress_report_type_enum
  )
ORDER BY pr.date DESC
LIMIT $4 OFFSET $3
`

type ListProgressReportsParams struct {
	ClientID uuid.UUID                  `json:"client_id"`
	Type     NullProgressReportTypeEnum `json:"type"`
	Offset   int32                      `json:"offset"`
	Limit    int32                      `json:"limit"`
}

type ListProgressReportsRow struct {
	ID                     uuid.UUID              `json:"id"`
	ClientID               uuid.UUID              `json:"client_id"`
	Date                   pgtype.Timestamptz     `json:"date"`
	Title                  *string                `json:"title"`
	ReportText             string                 `json:"report_text"`
	EmployeeID             *uuid.UUID             `json:"employee_id"`
	Type                   ProgressReportTypeEnum `json:"type"`
	EmotionalState         EmotionalStateEnum     `json:"emotional_state"`
	CreatedAt              pgtype.Timestamptz     `json:"created_at"`
	TotalCount             int64                  `json:"total_count"`
	EmployeeFirstName      string                 `json:"employee_first_name"`
	EmployeeLastName       string                 `json:"employee_last_name"`
	EmployeeProfilePicture *string                `json:"employee_profile_picture"`
}

func (q *Queries) ListProgressReports(ctx context.Context, arg ListProgressReportsParams) ([]ListProgressReportsRow, error) {
	rows, err := q.db.Query(ctx, listProgressReports,
		arg.ClientID,
		arg.Type,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgressReportsRow{}
	for rows.Next() {
		var i ListProgressReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Date,
			&i.Title,
			&i.ReportText,
			&i.EmployeeID,
			&i.Type,
			&i.EmotionalState,
			&i.CreatedAt,
			&i.TotalCount,
			&i.EmployeeFirstName,
			&i.EmployeeLastName,
			&i.EmployeeProfilePicture,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProgressReport = `-- name: UpdateProgressReport :one
UPDATE progress_report
SET
    employee_id = COALESCE($2, employee_id),
    title = COALESCE($3, title),
    date = COALESCE($4, date),
    report_text = COALESCE($5, report_text),
    type = COALESCE($6, type),
    emotional_state = COALESCE($7, emotional_state)
WHERE id = $1
RETURNING id, client_id, date, title, report_text, employee_id, type, emotional_state, created_at
`

type UpdateProgressReportParams struct {
	ID             uuid.UUID                  `json:"id"`
	EmployeeID     *uuid.UUID                 `json:"employee_id"`
	Title          *string                    `json:"title"`
	Date           pgtype.Timestamptz         `json:"date"`
	ReportText     *string                    `json:"report_text"`
	Type           NullProgressReportTypeEnum `json:"type"`
	EmotionalState NullEmotionalStateEnum     `json:"emotional_state"`
}

func (q *Queries) UpdateProgressReport(ctx context.Context, arg UpdateProgressReportParams) (ProgressReport, error) {
	row := q.db.QueryRow(ctx, updateProgressReport,
		arg.ID,
		arg.EmployeeID,
		arg.Title,
		arg.Date,
		arg.ReportText,
		arg.Type,
		arg.EmotionalState,
	)
	var i ProgressReport
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Date,
		&i.Title,
		&i.ReportText,
		&i.EmployeeID,
		&i.Type,
		&i.EmotionalState,
		&i.CreatedAt,
	)
	return i, err
}
