// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: intake_maturity.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIntakeMaturityAssessment = `-- name: CreateIntakeMaturityAssessment :one
INSERT INTO intake_maturity_assessments (
    intake_form_id,
    maturity_matrix_id,
    current_level,
    proposed_goals,
    notes
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, intake_form_id, maturity_matrix_id, current_level, proposed_goals, notes, created_at
`

type CreateIntakeMaturityAssessmentParams struct {
	IntakeFormID     uuid.UUID `json:"intake_form_id"`
	MaturityMatrixID uuid.UUID `json:"maturity_matrix_id"`
	CurrentLevel     int32     `json:"current_level"`
	ProposedGoals    []byte    `json:"proposed_goals"`
	Notes            *string   `json:"notes"`
}

func (q *Queries) CreateIntakeMaturityAssessment(ctx context.Context, arg CreateIntakeMaturityAssessmentParams) (IntakeMaturityAssessment, error) {
	row := q.db.QueryRow(ctx, createIntakeMaturityAssessment,
		arg.IntakeFormID,
		arg.MaturityMatrixID,
		arg.CurrentLevel,
		arg.ProposedGoals,
		arg.Notes,
	)
	var i IntakeMaturityAssessment
	err := row.Scan(
		&i.ID,
		&i.IntakeFormID,
		&i.MaturityMatrixID,
		&i.CurrentLevel,
		&i.ProposedGoals,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIntakeMaturityAssessment = `-- name: DeleteIntakeMaturityAssessment :exec
DELETE FROM intake_maturity_assessments
WHERE id = $1
`

func (q *Queries) DeleteIntakeMaturityAssessment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIntakeMaturityAssessment, id)
	return err
}

const getIntakeMaturityAssessment = `-- name: GetIntakeMaturityAssessment :one
SELECT 
    ima.id, ima.intake_form_id, ima.maturity_matrix_id, ima.current_level, ima.proposed_goals, ima.notes, ima.created_at,
    mm.topic_name
FROM intake_maturity_assessments ima
JOIN maturity_matrix mm ON ima.maturity_matrix_id = mm.id
WHERE ima.id = $1
`

type GetIntakeMaturityAssessmentRow struct {
	ID               uuid.UUID          `json:"id"`
	IntakeFormID     uuid.UUID          `json:"intake_form_id"`
	MaturityMatrixID uuid.UUID          `json:"maturity_matrix_id"`
	CurrentLevel     int32              `json:"current_level"`
	ProposedGoals    []byte             `json:"proposed_goals"`
	Notes            *string            `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	TopicName        string             `json:"topic_name"`
}

func (q *Queries) GetIntakeMaturityAssessment(ctx context.Context, id uuid.UUID) (GetIntakeMaturityAssessmentRow, error) {
	row := q.db.QueryRow(ctx, getIntakeMaturityAssessment, id)
	var i GetIntakeMaturityAssessmentRow
	err := row.Scan(
		&i.ID,
		&i.IntakeFormID,
		&i.MaturityMatrixID,
		&i.CurrentLevel,
		&i.ProposedGoals,
		&i.Notes,
		&i.CreatedAt,
		&i.TopicName,
	)
	return i, err
}

const getIntakeMaturityAssessments = `-- name: GetIntakeMaturityAssessments :many
SELECT 
    ima.id, ima.intake_form_id, ima.maturity_matrix_id, ima.current_level, ima.proposed_goals, ima.notes, ima.created_at,
    mm.topic_name
FROM intake_maturity_assessments ima
JOIN maturity_matrix mm ON ima.maturity_matrix_id = mm.id
WHERE ima.intake_form_id = $1
ORDER BY mm.topic_name
`

type GetIntakeMaturityAssessmentsRow struct {
	ID               uuid.UUID          `json:"id"`
	IntakeFormID     uuid.UUID          `json:"intake_form_id"`
	MaturityMatrixID uuid.UUID          `json:"maturity_matrix_id"`
	CurrentLevel     int32              `json:"current_level"`
	ProposedGoals    []byte             `json:"proposed_goals"`
	Notes            *string            `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	TopicName        string             `json:"topic_name"`
}

func (q *Queries) GetIntakeMaturityAssessments(ctx context.Context, intakeFormID uuid.UUID) ([]GetIntakeMaturityAssessmentsRow, error) {
	rows, err := q.db.Query(ctx, getIntakeMaturityAssessments, intakeFormID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetIntakeMaturityAssessmentsRow{}
	for rows.Next() {
		var i GetIntakeMaturityAssessmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.IntakeFormID,
			&i.MaturityMatrixID,
			&i.CurrentLevel,
			&i.ProposedGoals,
			&i.Notes,
			&i.CreatedAt,
			&i.TopicName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntakeMaturityAssessmentsByIntake = `-- name: ListIntakeMaturityAssessmentsByIntake :many
SELECT 
    ima.id, ima.intake_form_id, ima.maturity_matrix_id, ima.current_level, ima.proposed_goals, ima.notes, ima.created_at,
    mm.topic_name
FROM intake_maturity_assessments ima
JOIN maturity_matrix mm ON ima.maturity_matrix_id = mm.id
WHERE ima.intake_form_id = $1
ORDER BY mm.topic_name
LIMIT $2 OFFSET $3
`

type ListIntakeMaturityAssessmentsByIntakeParams struct {
	IntakeFormID uuid.UUID `json:"intake_form_id"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

type ListIntakeMaturityAssessmentsByIntakeRow struct {
	ID               uuid.UUID          `json:"id"`
	IntakeFormID     uuid.UUID          `json:"intake_form_id"`
	MaturityMatrixID uuid.UUID          `json:"maturity_matrix_id"`
	CurrentLevel     int32              `json:"current_level"`
	ProposedGoals    []byte             `json:"proposed_goals"`
	Notes            *string            `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	TopicName        string             `json:"topic_name"`
}

func (q *Queries) ListIntakeMaturityAssessmentsByIntake(ctx context.Context, arg ListIntakeMaturityAssessmentsByIntakeParams) ([]ListIntakeMaturityAssessmentsByIntakeRow, error) {
	rows, err := q.db.Query(ctx, listIntakeMaturityAssessmentsByIntake, arg.IntakeFormID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIntakeMaturityAssessmentsByIntakeRow{}
	for rows.Next() {
		var i ListIntakeMaturityAssessmentsByIntakeRow
		if err := rows.Scan(
			&i.ID,
			&i.IntakeFormID,
			&i.MaturityMatrixID,
			&i.CurrentLevel,
			&i.ProposedGoals,
			&i.Notes,
			&i.CreatedAt,
			&i.TopicName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIntakeMaturityAssessment = `-- name: UpdateIntakeMaturityAssessment :one
UPDATE intake_maturity_assessments
SET
    current_level = COALESCE($1, current_level),
    proposed_goals = COALESCE($2, proposed_goals),
    notes = COALESCE($3, notes)
WHERE id = $4
RETURNING id, intake_form_id, maturity_matrix_id, current_level, proposed_goals, notes, created_at
`

type UpdateIntakeMaturityAssessmentParams struct {
	CurrentLevel  *int32    `json:"current_level"`
	ProposedGoals []byte    `json:"proposed_goals"`
	Notes         *string   `json:"notes"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) UpdateIntakeMaturityAssessment(ctx context.Context, arg UpdateIntakeMaturityAssessmentParams) (IntakeMaturityAssessment, error) {
	row := q.db.QueryRow(ctx, updateIntakeMaturityAssessment,
		arg.CurrentLevel,
		arg.ProposedGoals,
		arg.Notes,
		arg.ID,
	)
	var i IntakeMaturityAssessment
	err := row.Scan(
		&i.ID,
		&i.IntakeFormID,
		&i.MaturityMatrixID,
		&i.CurrentLevel,
		&i.ProposedGoals,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
