// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leave_request.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLeaveRequest = `-- name: CreateLeaveRequest :one
INSERT INTO leave_requests (
    employee_id,
    created_by_employee_id,
    leave_type,
    start_date,
    end_date,
    reason,
    requested_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    NOW()
)
RETURNING id, employee_id, created_by_employee_id, leave_type, status, start_date, end_date, reason, decision_note, decided_by_employee_id, requested_at, decided_at, cancelled_at, created_at, updated_at
`

type CreateLeaveRequestParams struct {
	EmployeeID          uuid.UUID            `json:"employee_id"`
	CreatedByEmployeeID *uuid.UUID           `json:"created_by_employee_id"`
	LeaveType           LeaveRequestTypeEnum `json:"leave_type"`
	StartDate           pgtype.Date          `json:"start_date"`
	EndDate             pgtype.Date          `json:"end_date"`
	Reason              *string              `json:"reason"`
}

func (q *Queries) CreateLeaveRequest(ctx context.Context, arg CreateLeaveRequestParams) (LeaveRequest, error) {
	row := q.db.QueryRow(ctx, createLeaveRequest,
		arg.EmployeeID,
		arg.CreatedByEmployeeID,
		arg.LeaveType,
		arg.StartDate,
		arg.EndDate,
		arg.Reason,
	)
	var i LeaveRequest
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.CreatedByEmployeeID,
		&i.LeaveType,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.Reason,
		&i.DecisionNote,
		&i.DecidedByEmployeeID,
		&i.RequestedAt,
		&i.DecidedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
