// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leave_policy.sql

package db

import (
	"context"
)

const getActiveLeavePolicyByType = `-- name: GetActiveLeavePolicyByType :one
SELECT
    leave_type,
    requires_approval,
    deducts_balance,
    is_active,
    created_at,
    updated_at
FROM leave_policies
WHERE leave_type = $1::leave_request_type_enum
  AND is_active = TRUE
`

func (q *Queries) GetActiveLeavePolicyByType(ctx context.Context, leaveType LeaveRequestTypeEnum) (LeavePolicy, error) {
	row := q.db.QueryRow(ctx, getActiveLeavePolicyByType, leaveType)
	var i LeavePolicy
	err := row.Scan(
		&i.LeaveType,
		&i.RequiresApproval,
		&i.DeductsBalance,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
