// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AiGeneratedReport struct {
	ID         int64              `json:"id"`
	ReportType string             `json:"report_type"`
	Title      string             `json:"title"`
	Content    *string            `json:"content"`
	UserID     *int64             `json:"user_id"`
	UserType   string             `json:"user_type"`
	StartDate  pgtype.Timestamptz `json:"start_date"`
	EndDate    pgtype.Timestamptz `json:"end_date"`
	Updated    pgtype.Timestamptz `json:"updated"`
	Created    pgtype.Timestamptz `json:"created"`
}

type AiGeneratedWeeklyReport struct {
	ID         int64              `json:"id"`
	ReportText string             `json:"report_text"`
	GoalID     *int64             `json:"goal_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Assessment struct {
	ID       int64              `json:"id"`
	Content  *string            `json:"content"`
	DomainID *int64             `json:"domain_id"`
	Level    int32              `json:"level"`
	Updated  pgtype.Timestamptz `json:"updated"`
	Created  pgtype.Timestamptz `json:"created"`
}

type AssessmentDomain struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Assignment struct {
	ID            int64              `json:"id"`
	EmployeeID    int64              `json:"employee_id"`
	ClientID      int64              `json:"client_id"`
	StartDatetime pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime   pgtype.Timestamptz `json:"end_datetime"`
	Status        string             `json:"status"`
	Created       pgtype.Timestamptz `json:"created"`
}

type AttachmentFile struct {
	Uuid    uuid.UUID          `json:"uuid"`
	Name    string             `json:"name"`
	File    string             `json:"file"`
	Size    int32              `json:"size"`
	IsUsed  bool               `json:"is_used"`
	Tag     *string            `json:"tag"`
	Updated pgtype.Timestamptz `json:"updated"`
	Created pgtype.Timestamptz `json:"created"`
}

type CarePlan struct {
	ID          int64              `json:"id"`
	ClientID    *int64             `json:"client_id"`
	Description string             `json:"description"`
	StartDate   pgtype.Date        `json:"start_date"`
	EndDate     pgtype.Date        `json:"end_date"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CarePlanDomain struct {
	CarePlanID         int64 `json:"care_plan_id"`
	AssessmentDomainID int64 `json:"assessment_domain_id"`
}

type CareplanAtachement struct {
	ID          int64              `json:"id"`
	CareplanID  *int64             `json:"careplan_id"`
	Attachement string             `json:"attachement"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Name        *string            `json:"name"`
}

type Certification struct {
	ID         int64              `json:"id"`
	EmployeeID int64              `json:"employee_id"`
	Name       string             `json:"name"`
	IssuedBy   string             `json:"issued_by"`
	DateIssued pgtype.Date        `json:"date_issued"`
	Created    pgtype.Timestamptz `json:"created"`
}

type ClientAgreement struct {
	ID               int64              `json:"id"`
	ContractID       int64              `json:"contract_id"`
	AgreementDetails string             `json:"agreement_details"`
	Created          pgtype.Timestamptz `json:"created"`
}

type ClientAllergy struct {
	ID          int64              `json:"id"`
	ClientID    int64              `json:"client_id"`
	AllergyType string             `json:"allergy_type"`
	Severity    string             `json:"severity"`
	Reaction    string             `json:"reaction"`
	Notes       *string            `json:"notes"`
	Created     pgtype.Timestamptz `json:"created"`
}

type ClientCurrentLevel struct {
	ID       int64              `json:"id"`
	ClientID int64              `json:"client_id"`
	DomainID int64              `json:"domain_id"`
	Level    int32              `json:"level"`
	Content  *string            `json:"content"`
	Created  pgtype.Timestamptz `json:"created"`
}

type ClientDetail struct {
	ID                    int64              `json:"id"`
	UserID                int64              `json:"user_id"`
	FirstName             string             `json:"first_name"`
	LastName              string             `json:"last_name"`
	DateOfBirth           pgtype.Date        `json:"date_of_birth"`
	Identity              bool               `json:"identity"`
	Status                *string            `json:"status"`
	Bsn                   *string            `json:"bsn"`
	Source                *string            `json:"source"`
	Birthplace            *string            `json:"birthplace"`
	Email                 string             `json:"email"`
	PhoneNumber           *string            `json:"phone_number"`
	Organisation          *string            `json:"organisation"`
	Departement           *string            `json:"departement"`
	Gender                string             `json:"gender"`
	Filenumber            int32              `json:"filenumber"`
	ProfilePicture        *string            `json:"profile_picture"`
	Infix                 *string            `json:"infix"`
	Created               pgtype.Timestamptz `json:"created"`
	SenderID              *int64             `json:"sender_id"`
	LocationID            *int64             `json:"location_id"`
	IdentityAttachmentIds []byte             `json:"identity_attachment_ids"`
	DepartureReason       *string            `json:"departure_reason"`
	DepartureReport       *string            `json:"departure_report"`
	GpsPosition           []byte             `json:"gps_position"`
	MaturityDomains       []byte             `json:"maturity_domains"`
	Addresses             []byte             `json:"addresses"`
	LegalMeasure          *string            `json:"legal_measure"`
	HasUntakenMedications bool               `json:"has_untaken_medications"`
}

type ClientDiagnosis struct {
	ID                  int64              `json:"id"`
	Title               *string            `json:"title"`
	ClientID            int64              `json:"client_id"`
	DiagnosisCode       string             `json:"diagnosis_code"`
	Description         string             `json:"description"`
	DateOfDiagnosis     pgtype.Timestamptz `json:"date_of_diagnosis"`
	Severity            *string            `json:"severity"`
	Status              string             `json:"status"`
	DiagnosingClinician string             `json:"diagnosing_clinician"`
	Notes               *string            `json:"notes"`
	Created             pgtype.Timestamptz `json:"created"`
}

type ClientDocument struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	Documents        string             `json:"documents"`
	UploadedAt       pgtype.Timestamptz `json:"uploaded_at"`
	OriginalFilename *string            `json:"original_filename"`
	FileSize         *int64             `json:"file_size"`
	Created          pgtype.Timestamptz `json:"created"`
	Label            string             `json:"label"`
}

type ClientEmergencyContact struct {
	ID               int64              `json:"id"`
	ClientID         int64              `json:"client_id"`
	FirstName        *string            `json:"first_name"`
	LastName         *string            `json:"last_name"`
	Email            *string            `json:"email"`
	PhoneNumber      *string            `json:"phone_number"`
	Address          *string            `json:"address"`
	Relationship     *string            `json:"relationship"`
	RelationStatus   *string            `json:"relation_status"`
	Created          pgtype.Timestamptz `json:"created"`
	IsVerified       bool               `json:"is_verified"`
	Uuid             pgtype.UUID        `json:"uuid"`
	MedicalReports   bool               `json:"medical_reports"`
	IncidentsReports bool               `json:"incidents_reports"`
	GoalsReports     bool               `json:"goals_reports"`
}

type ClientEmployeeAssignment struct {
	ID         int64              `json:"id"`
	ClientID   int64              `json:"client_id"`
	EmployeeID int64              `json:"employee_id"`
	StartDate  pgtype.Date        `json:"start_date"`
	Role       string             `json:"role"`
	Created    pgtype.Timestamptz `json:"created"`
}

type ClientGoal struct {
	ID               int64              `json:"id"`
	ClientID         int64              `json:"client_id"`
	GoalName         string             `json:"goal_name"`
	GoalDetails      string             `json:"goal_details"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	AdministeredByID *int64             `json:"administered_by_id"`
}

type ClientMedication struct {
	ID               int64              `json:"id"`
	Name             string             `json:"name"`
	Dosage           string             `json:"dosage"`
	StartDate        pgtype.Date        `json:"start_date"`
	EndDate          pgtype.Date        `json:"end_date"`
	Notes            *string            `json:"notes"`
	SelfAdministered bool               `json:"self_administered"`
	Slots            []byte             `json:"slots"`
	ClientID         int64              `json:"client_id"`
	AdministeredByID *int64             `json:"administered_by_id"`
	IsCritical       bool               `json:"is_critical"`
	Updated          pgtype.Timestamptz `json:"updated"`
	Created          pgtype.Timestamptz `json:"created"`
}

type ClientMedicationRecord struct {
	ID                 int64              `json:"id"`
	ClientMedicationID int64              `json:"client_medication_id"`
	Status             *string            `json:"status"`
	Reason             *string            `json:"reason"`
	Time               pgtype.Timestamptz `json:"time"`
	Updated            pgtype.Timestamptz `json:"updated"`
	Created            pgtype.Timestamptz `json:"created"`
}

type ClientState struct {
	ID       int64              `json:"id"`
	Value    int32              `json:"value"`
	Type     string             `json:"type"`
	Content  *string            `json:"content"`
	ClientID int64              `json:"client_id"`
	Updated  pgtype.Timestamptz `json:"updated"`
	Created  pgtype.Timestamptz `json:"created"`
}

type ClientStatusHistory struct {
	ID        int64              `json:"id"`
	ClientID  int64              `json:"client_id"`
	Status    string             `json:"status"`
	StartDate pgtype.Timestamptz `json:"start_date"`
}

type CollaborationAgreement struct {
	ID                                int64              `json:"id"`
	ClientID                          int64              `json:"client_id"`
	ClientFullName                    string             `json:"client_full_name"`
	ClientSkn                         string             `json:"client_skn"`
	ClientNumber                      string             `json:"client_number"`
	ClientPhone                       string             `json:"client_phone"`
	ProbationFullName                 string             `json:"probation_full_name"`
	ProbationOrganization             string             `json:"probation_organization"`
	ProbationPhone                    string             `json:"probation_phone"`
	HealthcareInstitutionName         string             `json:"healthcare_institution_name"`
	HealthcareInstitutionOrganization string             `json:"healthcare_institution_organization"`
	HealthcareInstitutionPhone        string             `json:"healthcare_institution_phone"`
	HealthcareInstitutionFunction     string             `json:"healthcare_institution_function"`
	ContactAgreements                 string             `json:"contact_agreements"`
	PdfAttachmentID                   pgtype.UUID        `json:"pdf_attachment_id"`
	AttentionRisks                    []byte             `json:"attention_risks"`
	Updated                           pgtype.Timestamptz `json:"updated"`
	Created                           pgtype.Timestamptz `json:"created"`
}

type ConsentDeclaration struct {
	ID                            int64              `json:"id"`
	YouthName                     string             `json:"youth_name"`
	DateOfBirth                   pgtype.Date        `json:"date_of_birth"`
	ParentGuardianName            string             `json:"parent_guardian_name"`
	Address                       string             `json:"address"`
	YouthCareInstitution          string             `json:"youth_care_institution"`
	ProposedAssistanceDescription string             `json:"proposed_assistance_description"`
	StatementByRepresentative     string             `json:"statement_by_representative"`
	ParentGuardianSignatureDate   pgtype.Date        `json:"parent_guardian_signature_date"`
	JuvenileName                  *string            `json:"juvenile_name"`
	JuvenileSignatureDate         pgtype.Date        `json:"juvenile_signature_date"`
	RepresentativeName            string             `json:"representative_name"`
	RepresentativeSignatureDate   pgtype.Date        `json:"representative_signature_date"`
	ContactPersonName             string             `json:"contact_person_name"`
	ContactPhoneNumber            string             `json:"contact_phone_number"`
	ContactEmail                  string             `json:"contact_email"`
	ClientID                      int64              `json:"client_id"`
	Updated                       pgtype.Timestamptz `json:"updated"`
	Created                       pgtype.Timestamptz `json:"created"`
	PdfAttachmentID               pgtype.UUID        `json:"pdf_attachment_id"`
}

type Contact struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	PhoneNumber string `json:"phone_number"`
	Email       string `json:"email"`
}

type ContactRelationship struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	SoftDelete bool   `json:"soft_delete"`
}

type Contract struct {
	ID              int64              `json:"id"`
	TypeID          *int64             `json:"type_id"`
	Status          string             `json:"status"`
	StartDate       pgtype.Timestamptz `json:"start_date"`
	EndDate         pgtype.Timestamptz `json:"end_date"`
	ReminderPeriod  int32              `json:"reminder_period"`
	Tax             *int32             `json:"tax"`
	Price           pgtype.Numeric     `json:"price"`
	PriceFrequency  string             `json:"price_frequency"`
	Hours           *int32             `json:"hours"`
	HoursType       string             `json:"hours_type"`
	CareName        string             `json:"care_name"`
	CareType        string             `json:"care_type"`
	ClientID        int64              `json:"client_id"`
	SenderID        *int64             `json:"sender_id"`
	AttachmentIds   []byte             `json:"attachment_ids"`
	FinancingAct    string             `json:"financing_act"`
	FinancingOption string             `json:"financing_option"`
	DepartureReason *string            `json:"departure_reason"`
	DepartureReport *string            `json:"departure_report"`
	Updated         pgtype.Timestamptz `json:"updated"`
	Created         pgtype.Timestamptz `json:"created"`
}

type ContractAttachment struct {
	ID         int64              `json:"id"`
	ContractID int64              `json:"contract_id"`
	Name       string             `json:"name"`
	Attachment string             `json:"attachment"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ContractType struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type ContractWorkingHour struct {
	ID         int64              `json:"id"`
	ContractID int64              `json:"contract_id"`
	Minutes    int32              `json:"minutes"`
	Datetime   pgtype.Timestamptz `json:"datetime"`
	Notes      *string            `json:"notes"`
}

type CustomUser struct {
	ID             int64              `json:"id"`
	Password       string             `json:"password"`
	LastLogin      pgtype.Timestamptz `json:"last_login"`
	Email          string             `json:"email"`
	RoleID         int32              `json:"role_id"`
	IsActive       bool               `json:"is_active"`
	DateJoined     pgtype.Timestamptz `json:"date_joined"`
	ProfilePicture *string            `json:"profile_picture"`
}

type DataSharingStatement struct {
	ID                                     int64              `json:"id"`
	YouthName                              string             `json:"youth_name"`
	DateOfBirth                            pgtype.Date        `json:"date_of_birth"`
	ParentGuardianName                     string             `json:"parent_guardian_name"`
	Address                                string             `json:"address"`
	YouthCareInstitution                   string             `json:"youth_care_institution"`
	DataDescription                        string             `json:"data_description"`
	DataPurpose                            string             `json:"data_purpose"`
	ThirdPartyNames                        string             `json:"third_party_names"`
	Statement                              string             `json:"statement"`
	ParentGuardianSignatureName            string             `json:"parent_guardian_signature_name"`
	ParentGuardianSignature                string             `json:"parent_guardian_signature"`
	ParentGuardianSignatureDate            pgtype.Date        `json:"parent_guardian_signature_date"`
	JuvenileName                           *string            `json:"juvenile_name"`
	JuvenileSignatureDate                  pgtype.Date        `json:"juvenile_signature_date"`
	InstitutionRepresentativeName          string             `json:"institution_representative_name"`
	InstitutionRepresentativeSignature     string             `json:"institution_representative_signature"`
	InstitutionRepresentativeSignatureDate pgtype.Date        `json:"institution_representative_signature_date"`
	ContactPersonName                      string             `json:"contact_person_name"`
	ContactPhoneNumber                     string             `json:"contact_phone_number"`
	ContactEmail                           string             `json:"contact_email"`
	ClientID                               int64              `json:"client_id"`
	Updated                                pgtype.Timestamptz `json:"updated"`
	Created                                pgtype.Timestamptz `json:"created"`
}

type DbSetting struct {
	ID          int64  `json:"id"`
	OptionName  string `json:"option_name"`
	OptionValue string `json:"option_value"`
	OptionType  string `json:"option_type"`
}

type DomainGoal struct {
	ID                                 int64              `json:"id"`
	Title                              string             `json:"title"`
	Desc                               *string            `json:"desc"`
	DomainID                           *int64             `json:"domain_id"`
	ClientID                           int64              `json:"client_id"`
	CreatedByID                        *int64             `json:"created_by_id"`
	ReviewedByID                       *int64             `json:"reviewed_by_id"`
	SelectedMaturityMatrixAssessmentID *int64             `json:"selected_maturity_matrix_assessment_id"`
	IsApproved                         bool               `json:"is_approved"`
	Updated                            pgtype.Timestamptz `json:"updated"`
	Created                            pgtype.Timestamptz `json:"created"`
}

type DomainObjective struct {
	ID       int64              `json:"id"`
	Title    string             `json:"title"`
	Desc     *string            `json:"desc"`
	Rating   float64            `json:"rating"`
	GoalID   *int64             `json:"goal_id"`
	ClientID int64              `json:"client_id"`
	Updated  pgtype.Timestamptz `json:"updated"`
	Created  pgtype.Timestamptz `json:"created"`
}

type Education struct {
	ID              int64       `json:"id"`
	EmployeeID      int64       `json:"employee_id"`
	InstitutionName string      `json:"institution_name"`
	Degree          string      `json:"degree"`
	FieldOfStudy    string      `json:"field_of_study"`
	StartDate       pgtype.Date `json:"start_date"`
	EndDate         pgtype.Date `json:"end_date"`
}

type EmotionalState struct {
	ID               int64              `json:"id"`
	ClientID         int64              `json:"client_id"`
	Date             pgtype.Timestamptz `json:"date"`
	StateDescription string             `json:"state_description"`
	Intensity        int32              `json:"intensity"`
	Created          pgtype.Timestamptz `json:"created"`
}

type EmployeeProfile struct {
	ID                        int64              `json:"id"`
	UserID                    int64              `json:"user_id"`
	FirstName                 string             `json:"first_name"`
	LastName                  string             `json:"last_name"`
	Position                  *string            `json:"position"`
	Department                *string            `json:"department"`
	EmployeeNumber            *string            `json:"employee_number"`
	EmploymentNumber          *string            `json:"employment_number"`
	PrivateEmailAddress       *string            `json:"private_email_address"`
	Email                     string             `json:"email"`
	AuthenticationPhoneNumber *string            `json:"authentication_phone_number"`
	PrivatePhoneNumber        *string            `json:"private_phone_number"`
	WorkPhoneNumber           *string            `json:"work_phone_number"`
	DateOfBirth               pgtype.Date        `json:"date_of_birth"`
	HomeTelephoneNumber       *string            `json:"home_telephone_number"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	IsSubcontractor           *bool              `json:"is_subcontractor"`
	Gender                    *string            `json:"gender"`
	LocationID                *int64             `json:"location_id"`
	HasBorrowed               bool               `json:"has_borrowed"`
	OutOfService              *bool              `json:"out_of_service"`
	IsArchived                bool               `json:"is_archived"`
}

type Expense struct {
	ID            int64              `json:"id"`
	Amount        pgtype.Numeric     `json:"amount"`
	Tax           float64            `json:"tax"`
	Desc          *string            `json:"desc"`
	AttachmentIds []byte             `json:"attachment_ids"`
	LocationID    *int64             `json:"location_id"`
	Updated       pgtype.Timestamptz `json:"updated"`
	Created       pgtype.Timestamptz `json:"created"`
}

type Experience struct {
	ID          int64              `json:"id"`
	EmployeeID  int64              `json:"employee_id"`
	JobTitle    string             `json:"job_title"`
	CompanyName string             `json:"company_name"`
	StartDate   pgtype.Date        `json:"start_date"`
	EndDate     pgtype.Date        `json:"end_date"`
	Description *string            `json:"description"`
	Created     pgtype.Timestamptz `json:"created"`
}

type Feedback struct {
	ID           int64              `json:"id"`
	AuthorID     *int64             `json:"author_id"`
	ClientID     int64              `json:"client_id"`
	Date         pgtype.Date        `json:"date"`
	FeedbackText string             `json:"feedback_text"`
	Created      pgtype.Timestamptz `json:"created"`
}

type FrameworkAgreement struct {
	ID               int64              `json:"id"`
	ClientID         int64              `json:"client_id"`
	AgreementDetails string             `json:"agreement_details"`
	Created          pgtype.Timestamptz `json:"created"`
}

type GoalHistory struct {
	ID     int64       `json:"id"`
	Rating float64     `json:"rating"`
	Date   pgtype.Date `json:"date"`
	GoalID int64       `json:"goal_id"`
}

type GoalsReport struct {
	ID           int64              `json:"id"`
	GoalID       *int64             `json:"goal_id"`
	Title        string             `json:"title"`
	ReportText   string             `json:"report_text"`
	Rating       *int32             `json:"rating"`
	CreatedAtSys pgtype.Timestamptz `json:"created_at_sys"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Group struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type GroupAccess struct {
	ID         int64              `json:"id"`
	EmployeeID int64              `json:"employee_id"`
	GroupID    int64              `json:"group_id"`
	StartDate  pgtype.Timestamptz `json:"start_date"`
	EndDate    pgtype.Timestamptz `json:"end_date"`
	Updated    pgtype.Timestamptz `json:"updated"`
	Created    pgtype.Timestamptz `json:"created"`
}

type Incident struct {
	ID                      int64              `json:"id"`
	EmployeeFullname        string             `json:"employee_fullname"`
	EmployeePosition        string             `json:"employee_position"`
	LocationID              *int64             `json:"location_id"`
	ReporterInvolvement     string             `json:"reporter_involvement"`
	InformWho               []byte             `json:"inform_who"`
	IncidentDate            pgtype.Date        `json:"incident_date"`
	RuntimeIncident         string             `json:"runtime_incident"`
	IncidentType            string             `json:"incident_type"`
	PassingAway             bool               `json:"passing_away"`
	SelfHarm                bool               `json:"self_harm"`
	Violence                bool               `json:"violence"`
	FireWaterDamage         bool               `json:"fire_water_damage"`
	Accident                bool               `json:"accident"`
	ClientAbsence           bool               `json:"client_absence"`
	Medicines               bool               `json:"medicines"`
	Organization            bool               `json:"organization"`
	UseProhibitedSubstances bool               `json:"use_prohibited_substances"`
	OtherNotifications      bool               `json:"other_notifications"`
	SeverityOfIncident      string             `json:"severity_of_incident"`
	IncidentExplanation     *string            `json:"incident_explanation"`
	RecurrenceRisk          string             `json:"recurrence_risk"`
	IncidentPreventSteps    *string            `json:"incident_prevent_steps"`
	IncidentTakenMeasures   *string            `json:"incident_taken_measures"`
	Technical               []byte             `json:"technical"`
	Organizational          []byte             `json:"organizational"`
	MeseWorker              []byte             `json:"mese_worker"`
	ClientOptions           []byte             `json:"client_options"`
	OtherCause              *string            `json:"other_cause"`
	CauseExplanation        *string            `json:"cause_explanation"`
	PhysicalInjury          string             `json:"physical_injury"`
	PhysicalInjuryDesc      *string            `json:"physical_injury_desc"`
	PsychologicalDamage     string             `json:"psychological_damage"`
	PsychologicalDamageDesc *string            `json:"psychological_damage_desc"`
	NeededConsultation      string             `json:"needed_consultation"`
	Succession              []byte             `json:"succession"`
	SuccessionDesc          *string            `json:"succession_desc"`
	Other                   bool               `json:"other"`
	OtherDesc               *string            `json:"other_desc"`
	AdditionalAppointments  *string            `json:"additional_appointments"`
	EmployeeAbsenteeism     []byte             `json:"employee_absenteeism"`
	ClientID                int64              `json:"client_id"`
	SoftDelete              bool               `json:"soft_delete"`
	Updated                 pgtype.Timestamptz `json:"updated"`
	Created                 pgtype.Timestamptz `json:"created"`
}

type IncidentDetail struct {
	ID               int64              `json:"id"`
	ReportedByID     int64              `json:"reported_by_id"`
	DateReported     pgtype.Timestamptz `json:"date_reported"`
	DateOfIncident   pgtype.Timestamptz `json:"date_of_incident"`
	Location         string             `json:"location"`
	Description      string             `json:"description"`
	ActionTaken      *string            `json:"action_taken"`
	FollowUpRequired bool               `json:"follow_up_required"`
	FollowUpDate     pgtype.Date        `json:"follow_up_date"`
	Notes            *string            `json:"notes"`
	Status           string             `json:"status"`
}

type IncidentInvolvedChild struct {
	IncidentID int64 `json:"incident_id"`
	ClientID   int64 `json:"client_id"`
}

type Invoice struct {
	ID              int64              `json:"id"`
	InvoiceNumber   string             `json:"invoice_number"`
	IssueDate       pgtype.Date        `json:"issue_date"`
	DueDate         pgtype.Date        `json:"due_date"`
	Status          string             `json:"status"`
	InvoiceDetails  []byte             `json:"invoice_details"`
	TotalAmount     pgtype.Numeric     `json:"total_amount"`
	PdfAttachmentID pgtype.UUID        `json:"pdf_attachment_id"`
	ExtraContent    *string            `json:"extra_content"`
	ClientID        int64              `json:"client_id"`
	Updated         pgtype.Timestamptz `json:"updated"`
	Created         pgtype.Timestamptz `json:"created"`
}

type InvoiceContract struct {
	ID          int64              `json:"id"`
	InvoiceID   *int64             `json:"invoice_id"`
	ContractID  *int64             `json:"contract_id"`
	PreVatTotal pgtype.Numeric     `json:"pre_vat_total"`
	VatRate     pgtype.Numeric     `json:"vat_rate"`
	VatAmount   pgtype.Numeric     `json:"vat_amount"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Updated     pgtype.Timestamptz `json:"updated"`
	Created     pgtype.Timestamptz `json:"created"`
}

type InvoiceHistory struct {
	ID            int64              `json:"id"`
	PaymentMethod *string            `json:"payment_method"`
	Amount        pgtype.Numeric     `json:"amount"`
	Updated       pgtype.Timestamptz `json:"updated"`
	Created       pgtype.Timestamptz `json:"created"`
	InvoiceID     int64              `json:"invoice_id"`
}

type Location struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Address  string `json:"address"`
	Capacity *int32 `json:"capacity"`
}

type MaturityMatrix struct {
	ID         int64              `json:"id"`
	ClientID   int64              `json:"client_id"`
	StartDate  pgtype.Date        `json:"start_date"`
	EndDate    pgtype.Date        `json:"end_date"`
	IsApproved bool               `json:"is_approved"`
	Updated    pgtype.Timestamptz `json:"updated"`
	Created    pgtype.Timestamptz `json:"created"`
}

type Measurement struct {
	ID              int64              `json:"id"`
	ClientID        int64              `json:"client_id"`
	Date            pgtype.Date        `json:"date"`
	MeasurementType string             `json:"measurement_type"`
	Value           float64            `json:"value"`
	Created         pgtype.Timestamptz `json:"created"`
}

type Notification struct {
	ID       int64              `json:"id"`
	Event    string             `json:"event"`
	Title    *string            `json:"title"`
	Content  *string            `json:"content"`
	IsRead   bool               `json:"is_read"`
	Metadata []byte             `json:"metadata"`
	Created  pgtype.Timestamptz `json:"created"`
}

type ObjectiveHistory struct {
	ID          int64       `json:"id"`
	Rating      float64     `json:"rating"`
	Week        int32       `json:"week"`
	Date        pgtype.Date `json:"date"`
	ObjectiveID int64       `json:"objective_id"`
	Content     *string     `json:"content"`
}

type ObjectiveProgressReport struct {
	ID          int64              `json:"id"`
	ObjectiveID int64              `json:"objective_id"`
	Title       string             `json:"title"`
	ReportText  *string            `json:"report_text"`
	Rating      float64            `json:"rating"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Observation struct {
	ID              int64              `json:"id"`
	ClientID        int64              `json:"client_id"`
	Category        *string            `json:"category"`
	Date            pgtype.Date        `json:"date"`
	ObservationText string             `json:"observation_text"`
	Created         pgtype.Timestamptz `json:"created"`
}

type Permission struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	Resource string `json:"resource"`
	Method   string `json:"method"`
}

type PhysicalState struct {
	ID       int64              `json:"id"`
	ClientID int64              `json:"client_id"`
	Date     pgtype.Timestamptz `json:"date"`
	Symptoms string             `json:"symptoms"`
	Severity int32              `json:"severity"`
	Created  pgtype.Timestamptz `json:"created"`
}

type ProgressReport struct {
	ID             int64              `json:"id"`
	ClientID       int64              `json:"client_id"`
	Date           pgtype.Timestamptz `json:"date"`
	Title          *string            `json:"title"`
	ReportText     string             `json:"report_text"`
	AuthorID       *int64             `json:"author_id"`
	Type           string             `json:"type"`
	EmotionalState string             `json:"emotional_state"`
	Created        pgtype.Timestamptz `json:"created"`
}

type ProtectedEmail struct {
	Uuid      uuid.UUID          `json:"uuid"`
	Email     string             `json:"email"`
	Subject   *string            `json:"subject"`
	Content   *string            `json:"content"`
	EmailType string             `json:"email_type"`
	ExpiredAt pgtype.Timestamptz `json:"expired_at"`
	Metadata  []byte             `json:"metadata"`
	Passkey   string             `json:"passkey"`
	Created   pgtype.Timestamptz `json:"created"`
}

type Provision struct {
	ID               int64              `json:"id"`
	ContractID       int64              `json:"contract_id"`
	ProvisionDetails string             `json:"provision_details"`
	Created          pgtype.Timestamptz `json:"created"`
}

type RiskAssessment struct {
	ID                             int64              `json:"id"`
	ClientID                       int64              `json:"client_id"`
	DateOfBirth                    pgtype.Date        `json:"date_of_birth"`
	Gender                         string             `json:"gender"`
	DateOfIntake                   pgtype.Timestamptz `json:"date_of_intake"`
	IntakerPositionName            string             `json:"intaker_position_name"`
	FamilySituation                string             `json:"family_situation"`
	EducationWork                  string             `json:"education_work"`
	CurrentLivingSituation         string             `json:"current_living_situation"`
	SocialNetwork                  string             `json:"social_network"`
	PreviousAssistance             string             `json:"previous_assistance"`
	BehaviourAtSchoolWork          string             `json:"behaviour_at_school_work"`
	PeopleSkills                   string             `json:"people_skills"`
	EmotionalStatus                string             `json:"emotional_status"`
	SelfImageSelfConfidence        string             `json:"self_image_self_confidence"`
	StressFactors                  string             `json:"stress_factors"`
	CommittedOffencesDescription   string             `json:"committed_offences_description"`
	OffencesFrequencySeriousness   string             `json:"offences_frequency_seriousness"`
	AgeFirstOffense                string             `json:"age_first_offense"`
	CircumstancesSurroundingCrimes string             `json:"circumstances_surrounding_crimes"`
	OffensesRecations              string             `json:"offenses_recations"`
	PersonalRiskFactors            string             `json:"personal_risk_factors"`
	EnvironmentalRiskFactors       string             `json:"environmental_risk_factors"`
	BehaviourRecurrenceRisk        string             `json:"behaviour_recurrence_risk"`
	AbuseSubstanceRisk             string             `json:"abuse_substance_risk"`
	PersonStrengths                string             `json:"person_strengths"`
	PositiveInfluences             string             `json:"positive_influences"`
	AvailableSupportAssistance     string             `json:"available_support_assistance"`
	PersonStrategies               string             `json:"person_strategies"`
	SpecificNeeds                  string             `json:"specific_needs"`
	RecommendedInterventions       string             `json:"recommended_interventions"`
	OtherAgenciesInvolvement       string             `json:"other_agencies_involvement"`
	RiskManagementPlanOfActions    string             `json:"risk_management_plan_of_actions"`
	FindingsSummary                string             `json:"findings_summary"`
	InstitutionAdvice              string             `json:"institution_advice"`
	Inclusion                      string             `json:"inclusion"`
	IntakerName                    string             `json:"intaker_name"`
	ReportDate                     pgtype.Date        `json:"report_date"`
	RegularEvaluationPlan          string             `json:"regular_evaluation_plan"`
	SuccessCriteria                string             `json:"success_criteria"`
	TimeTable                      string             `json:"time_table"`
	PdfAttachmentID                pgtype.UUID        `json:"pdf_attachment_id"`
	Updated                        pgtype.Timestamptz `json:"updated"`
	Created                        pgtype.Timestamptz `json:"created"`
}

type Role struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type RolePermission struct {
	RoleID       int32 `json:"role_id"`
	PermissionID int32 `json:"permission_id"`
}

type SelectedMaturityMatrixAssessment struct {
	ID               int64 `json:"id"`
	MaturityMatrixID int64 `json:"maturity_matrix_id"`
	AssessmentID     int64 `json:"assessment_id"`
}

type Sender struct {
	ID           int64              `json:"id"`
	Types        string             `json:"types"`
	Name         string             `json:"name"`
	Address      *string            `json:"address"`
	PostalCode   *string            `json:"postal_code"`
	Place        *string            `json:"place"`
	Land         *string            `json:"land"`
	Kvknumber    *string            `json:"kvknumber"`
	Btwnumber    *string            `json:"btwnumber"`
	PhoneNumber  *string            `json:"phone_number"`
	ClientNumber *string            `json:"client_number"`
	EmailAdress  *string            `json:"email_adress"`
	Contacts     []byte             `json:"contacts"`
	IsArchived   bool               `json:"is_archived"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type SenderAudit struct {
	ID        int64              `json:"id"`
	SenderID  int64              `json:"sender_id"`
	ChangedBy string             `json:"changed_by"`
	ChangedAt pgtype.Timestamptz `json:"changed_at"`
	OldData   []byte             `json:"old_data"`
	NewData   []byte             `json:"new_data"`
}

type SenderContactRelation struct {
	ID           int64 `json:"id"`
	ClientTypeID int64 `json:"client_type_id"`
	ContactID    int64 `json:"contact_id"`
}

type Session struct {
	ID           uuid.UUID          `json:"id"`
	RefreshToken string             `json:"refresh_token"`
	UserAgent    string             `json:"user_agent"`
	ClientIp     string             `json:"client_ip"`
	IsBlocked    bool               `json:"is_blocked"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UserID       int64              `json:"user_id"`
}

type TemporaryFile struct {
	ID         uuid.UUID          `json:"id"`
	File       string             `json:"file"`
	UploadedAt pgtype.Timestamptz `json:"uploaded_at"`
}

type Treatment struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	TreatmentName string             `json:"treatment_name"`
	TreatmentDate string             `json:"treatment_date"`
	Created       pgtype.Timestamptz `json:"created"`
}

type WeeklyReportSummary struct {
	ID          int64              `json:"id"`
	ClientID    int64              `json:"client_id"`
	SummaryText string             `json:"summary_text"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type YouthCareIntake struct {
	ID                          int64              `json:"id"`
	ClientID                    int64              `json:"client_id"`
	Name                        string             `json:"name"`
	DateOfBirth                 pgtype.Date        `json:"date_of_birth"`
	Gender                      string             `json:"gender"`
	Nationality                 string             `json:"nationality"`
	Bsn                         string             `json:"bsn"`
	Address                     string             `json:"address"`
	Postcode                    string             `json:"postcode"`
	Residence                   string             `json:"residence"`
	PhoneNumber                 string             `json:"phone_number"`
	Email                       string             `json:"email"`
	ReferrerName                string             `json:"referrer_name"`
	ReferrerOrganization        string             `json:"referrer_organization"`
	ReferrerFunction            string             `json:"referrer_function"`
	ReferrerPhoneNumber         string             `json:"referrer_phone_number"`
	ReferrerEmail               string             `json:"referrer_email"`
	ServiceChoice               string             `json:"service_choice"`
	FinancingActs               string             `json:"financing_acts"`
	FinancingOptions            string             `json:"financing_options"`
	FinancingOther              *string            `json:"financing_other"`
	RegistrationReason          string             `json:"registration_reason"`
	CurrentSituationBackground  string             `json:"current_situation_background"`
	PreviousAidAgenciesInvolved bool               `json:"previous_aid_agencies_involved"`
	PreviousAidAgenciesDetails  *string            `json:"previous_aid_agencies_details"`
	MedicalConditions           bool               `json:"medical_conditions"`
	MedicalConditionsDetails    *string            `json:"medical_conditions_details"`
	MedicationUse               bool               `json:"medication_use"`
	MedicationDetails           *string            `json:"medication_details"`
	AllergiesOrDietaryNeeds     bool               `json:"allergies_or_dietary_needs"`
	AllergiesOrDietaryDetails   *string            `json:"allergies_or_dietary_details"`
	Addictions                  bool               `json:"addictions"`
	AddictionsDetails           *string            `json:"addictions_details"`
	SchoolOrDaytimeActivities   bool               `json:"school_or_daytime_activities"`
	SchoolDaytimeName           *string            `json:"school_daytime_name"`
	CurrentClassLevel           *string            `json:"current_class_level"`
	SchoolContactPerson         *string            `json:"school_contact_person"`
	SchoolContactPhone          *string            `json:"school_contact_phone"`
	SchoolContactEmail          *string            `json:"school_contact_email"`
	ImportantPeople             *string            `json:"important_people"`
	ExternalSupervisorsInvolved bool               `json:"external_supervisors_involved"`
	ExternalSupervisorsDetails  *string            `json:"external_supervisors_details"`
	SpecialCircumstances        *string            `json:"special_circumstances"`
	Updated                     pgtype.Timestamptz `json:"updated"`
	Created                     pgtype.Timestamptz `json:"created"`
}
