// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ActivateDueScheduledInCareClients(ctx context.Context) ([]uuid.UUID, error)
	ActivateDueScheduledOutOfCareClients(ctx context.Context) ([]uuid.UUID, error)
	AddEducationToEmployeeProfile(ctx context.Context, arg AddEducationToEmployeeProfileParams) (EmployeeEducation, error)
	AddEmployeeCertification(ctx context.Context, arg AddEmployeeCertificationParams) (Certification, error)
	AddEmployeeContractDetails(ctx context.Context, arg AddEmployeeContractDetailsParams) (EmployeeProfile, error)
	AddEmployeeExperience(ctx context.Context, arg AddEmployeeExperienceParams) (EmployeeExperience, error)
	AddEventClientAttendee(ctx context.Context, arg AddEventClientAttendeeParams) error
	AddEventClientAttendeesBatch(ctx context.Context, arg AddEventClientAttendeesBatchParams) error
	AddEventEmployeeAttendee(ctx context.Context, arg AddEventEmployeeAttendeeParams) error
	AddEventEmployeeAttendeesBatch(ctx context.Context, arg AddEventEmployeeAttendeesBatchParams) error
	AddEventReminder(ctx context.Context, arg AddEventReminderParams) (AddEventReminderRow, error)
	// Bulk-insert permission IDs into a role (idempotent).
	AddPermissionsToRole(ctx context.Context, arg AddPermissionsToRoleParams) error
	// Bulk-insert explicit overrides for a user (idempotent by replacement flow).
	AddUserPermissionOverrides(ctx context.Context, arg AddUserPermissionOverridesParams) error
	ApplyLeaveBalanceDeduction(ctx context.Context, arg ApplyLeaveBalanceDeductionParams) (LeaveBalance, error)
	ApplyLeaveBalanceTotalAdjustment(ctx context.Context, arg ApplyLeaveBalanceTotalAdjustmentParams) (LeaveBalance, error)
	ApproveOrRejectClientLocationTransfer(ctx context.Context, arg ApproveOrRejectClientLocationTransferParams) error
	// Select the columns from the inserted row AND join to get the user_id
	AssignEmployee(ctx context.Context, arg AssignEmployeeParams) (AssignEmployeeRow, error)
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	AssignSender(ctx context.Context, arg AssignSenderParams) (ClientDetail, error)
	BulkCreateAuditRecords(ctx context.Context, arg []BulkCreateAuditRecordsParams) (int64, error)
	CancelCalendarEvent(ctx context.Context, id uuid.UUID) error
	CancelClientGoalByID(ctx context.Context, arg CancelClientGoalByIDParams) (ClientGoal, error)
	CheckAllShiftsExist(ctx context.Context, arg CheckAllShiftsExistParams) (bool, error)
	// ---------- 6. CHECK UTILITIES ----------
	// Returns true/false whether the user has the named permission.
	CheckUserPermission(ctx context.Context, arg CheckUserPermissionParams) (bool, error)
	CloneHandbookTemplateToDraft(ctx context.Context, arg CloneHandbookTemplateToDraftParams) (CloneHandbookTemplateToDraftRow, error)
	CompleteEmployeeHandbookStep(ctx context.Context, arg CompleteEmployeeHandbookStepParams) (EmployeeHandbookStepProgress, error)
	ConfirmIncident(ctx context.Context, arg ConfirmIncidentParams) (int64, error)
	ContractEndCount(ctx context.Context) (int64, error)
	CountActiveGoalsByClientID(ctx context.Context, clientID uuid.UUID) (int64, error)
	CountAllIncidents(ctx context.Context, arg CountAllIncidentsParams) (int64, error)
	CountBilledCalendarEventsByInvoice(ctx context.Context, invoiceID uuid.UUID) (int64, error)
	CountEligibleEmployeesForHandbookAssignment(ctx context.Context, arg CountEligibleEmployeesForHandbookAssignmentParams) (int64, error)
	CountEmployeeHandbookAssignments(ctx context.Context, arg CountEmployeeHandbookAssignmentsParams) (int64, error)
	CountEmployeeProfile(ctx context.Context, arg CountEmployeeProfileParams) (int64, error)
	CountHandbookStepsByTemplateID(ctx context.Context, templateID uuid.UUID) (int32, error)
	CountInvoiceLineCalendarEventsByInvoice(ctx context.Context, invoiceID uuid.UUID) (int64, error)
	CountRegistrationForms(ctx context.Context, arg CountRegistrationFormsParams) (int64, error)
	CountRemainingRequiredHandbookSteps(ctx context.Context, employeeHandbookID uuid.UUID) (int32, error)
	CountScheduleOverlapsForEmployee(ctx context.Context, arg CountScheduleOverlapsForEmployeeParams) (int64, error)
	CountSenders(ctx context.Context, includeArchived *bool) (int64, error)
	CreateAiGeneratedReport(ctx context.Context, arg CreateAiGeneratedReportParams) (AiGeneratedReport, error)
	CreateAppointmentCard(ctx context.Context, arg CreateAppointmentCardParams) (AppointmentCard, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (AttachmentFile, error)
	CreateAuditRecord(ctx context.Context, arg CreateAuditRecordParams) error
	CreateCalendarEvent(ctx context.Context, arg CreateCalendarEventParams) (CalendarEvent, error)
	CreateClientDetails(ctx context.Context, arg CreateClientDetailsParams) (ClientDetail, error)
	// ==========================================
	// Client Medical (v2)
	// Diagnoses + Medication Orders
	// ==========================================
	CreateClientDiagnosis(ctx context.Context, arg CreateClientDiagnosisParams) (ClientDiagnosis, error)
	CreateClientDocument(ctx context.Context, arg CreateClientDocumentParams) (ClientDocument, error)
	CreateClientGoalsFromIntakeAssessments(ctx context.Context, arg CreateClientGoalsFromIntakeAssessmentsParams) ([]CreateClientGoalsFromIntakeAssessmentsRow, error)
	CreateClientLocationTransfer(ctx context.Context, arg CreateClientLocationTransferParams) error
	CreateClientMedicationOrder(ctx context.Context, arg CreateClientMedicationOrderParams) (ClientMedicationOrder, error)
	CreateClientStatusHistory(ctx context.Context, arg CreateClientStatusHistoryParams) (ClientStatusHistory, error)
	CreateContract(ctx context.Context, arg CreateContractParams) (Contract, error)
	CreateContractReminder(ctx context.Context, arg CreateContractReminderParams) (ContractReminder, error)
	CreateContractType(ctx context.Context, name string) (ContractType, error)
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error)
	CreateEmemrgencyContact(ctx context.Context, arg CreateEmemrgencyContactParams) (ClientEmergencyContact, error)
	CreateEmployeeHandbookAssignmentHistory(ctx context.Context, arg CreateEmployeeHandbookAssignmentHistoryParams) (EmployeeHandbookAssignmentHistory, error)
	CreateEmployeeHandbookFromTemplate(ctx context.Context, arg CreateEmployeeHandbookFromTemplateParams) (CreateEmployeeHandbookFromTemplateRow, error)
	CreateEmployeeProfile(ctx context.Context, arg CreateEmployeeProfileParams) (EmployeeProfile, error)
	CreateGoalEvaluation(ctx context.Context, arg CreateGoalEvaluationParams) (ClientGoalEvaluation, error)
	CreateHandbookStep(ctx context.Context, arg CreateHandbookStepParams) (HandbookStep, error)
	CreateHandbookTemplateForDepartment(ctx context.Context, arg CreateHandbookTemplateForDepartmentParams) (HandbookTemplate, error)
	CreateIncident(ctx context.Context, arg CreateIncidentParams) (CreateIncidentRow, error)
	CreateIntakeForm(ctx context.Context, arg CreateIntakeFormParams) (IntakeForm, error)
	CreateIntakeTopicAssessment(ctx context.Context, arg CreateIntakeTopicAssessmentParams) (IntakeTopicAssessment, error)
	CreateIntakeTopicAssessmentsBatch(ctx context.Context, arg CreateIntakeTopicAssessmentsBatchParams) ([]CreateIntakeTopicAssessmentsBatchRow, error)
	// ////////////////////// Invoices //////////////////////
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	// ////////////////////// Invoice Lines //////////////////////
	CreateInvoiceLine(ctx context.Context, arg CreateInvoiceLineParams) (InvoiceLine, error)
	// ////////////////////// Line Sources (Appointments) //////////////////////
	CreateInvoiceLineCalendarEvent(ctx context.Context, arg CreateInvoiceLineCalendarEventParams) (InvoiceLineCalendarEvent, error)
	// ////////////////////// Batch Runs //////////////////////
	CreateInvoiceRun(ctx context.Context, arg CreateInvoiceRunParams) (InvoiceRun, error)
	CreateInvoiceRunItem(ctx context.Context, arg CreateInvoiceRunItemParams) (InvoiceRunItem, error)
	CreateLateArrival(ctx context.Context, arg CreateLateArrivalParams) (LateArrival, error)
	CreateLeaveBalanceAdjustmentAudit(ctx context.Context, arg CreateLeaveBalanceAdjustmentAuditParams) (LeaveBalanceAdjustment, error)
	CreateLeaveRequest(ctx context.Context, arg CreateLeaveRequestParams) (LeaveRequest, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateManualClientGoal(ctx context.Context, arg CreateManualClientGoalParams) (ClientGoal, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateOrganisation(ctx context.Context, arg CreateOrganisationParams) (Organisation, error)
	// ////////////////////// Payments //////////////////////
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (InvoicePaymentHistory, error)
	CreateProgressReport(ctx context.Context, arg CreateProgressReportParams) (ProgressReport, error)
	CreateRegistrationForm(ctx context.Context, arg CreateRegistrationFormParams) (RegistrationForm, error)
	CreateReviewUpdatedClientGoal(ctx context.Context, arg CreateReviewUpdatedClientGoalParams) (ClientGoal, error)
	// ---------- 1. ROLES ----------
	// Insert a new role and return the created row.
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSchedule(ctx context.Context, arg CreateScheduleParams) (CreateScheduleRow, error)
	CreateSeedIntakeForm(ctx context.Context, arg CreateSeedIntakeFormParams) (CreateSeedIntakeFormRow, error)
	CreateSender(ctx context.Context, arg CreateSenderParams) (Sender, error)
	CreateSenderInvoiceTemplate(ctx context.Context, arg CreateSenderInvoiceTemplateParams) ([]uuid.UUID, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateShift(ctx context.Context, arg CreateShiftParams) (LocationShift, error)
	CreateShiftSwapRequest(ctx context.Context, arg CreateShiftSwapRequestParams) (ShiftSwapRequest, error)
	CreateTemp2FaSecret(ctx context.Context, arg CreateTemp2FaSecretParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CustomUser, error)
	DeleteAssignedEmployee(ctx context.Context, id uuid.UUID) (AssignedEmployee, error)
	DeleteAttachment(ctx context.Context, argUuid uuid.UUID) (AttachmentFile, error)
	DeleteAttendeesByEventID(ctx context.Context, eventID uuid.UUID) error
	DeleteClientDiagnosis(ctx context.Context, arg DeleteClientDiagnosisParams) (ClientDiagnosis, error)
	DeleteClientDocument(ctx context.Context, arg DeleteClientDocumentParams) (ClientDocument, error)
	DeleteClientMedicationOrder(ctx context.Context, arg DeleteClientMedicationOrderParams) error
	DeleteContractType(ctx context.Context, id uuid.UUID) error
	DeleteDepartment(ctx context.Context, id uuid.UUID) error
	DeleteEmergencyContact(ctx context.Context, id uuid.UUID) (ClientEmergencyContact, error)
	DeleteEmployeeCertification(ctx context.Context, id uuid.UUID) (Certification, error)
	DeleteEmployeeEducation(ctx context.Context, id uuid.UUID) (EmployeeEducation, error)
	DeleteEmployeeExperience(ctx context.Context, id uuid.UUID) (EmployeeExperience, error)
	DeleteHandbookStepByID(ctx context.Context, id uuid.UUID) error
	DeleteIncident(ctx context.Context, id uuid.UUID) error
	DeleteIntakeTopicAssessmentsByIntakeForm(ctx context.Context, intakeFormID uuid.UUID) error
	DeleteIntakeTopicsAssessment(ctx context.Context, id uuid.UUID) error
	DeleteInvoice(ctx context.Context, id uuid.UUID) error
	DeleteInvoiceLinesByInvoice(ctx context.Context, invoiceID uuid.UUID) error
	DeleteLocation(ctx context.Context, id uuid.UUID) (Location, error)
	DeleteOrganisation(ctx context.Context, id uuid.UUID) (Organisation, error)
	DeletePayment(ctx context.Context, id uuid.UUID) (InvoicePaymentHistory, error)
	DeleteProgressReport(ctx context.Context, id uuid.UUID) error
	DeleteRegistrationForm(ctx context.Context, id uuid.UUID) error
	DeleteRemindersByEventID(ctx context.Context, eventID uuid.UUID) error
	DeleteSchedule(ctx context.Context, id uuid.UUID) error
	DeleteSender(ctx context.Context, id uuid.UUID) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteShift(ctx context.Context, id uuid.UUID) error
	// Removes all explicit overrides for the given user.
	DeleteUserPermissionOverrides(ctx context.Context, userID uuid.UUID) error
	DischargeOverview(ctx context.Context, arg DischargeOverviewParams) ([]DischargeOverviewRow, error)
	Enable2Fa(ctx context.Context, arg Enable2FaParams) (int64, error)
	EnsureLeaveBalanceForYear(ctx context.Context, arg EnsureLeaveBalanceForYearParams) error
	ExpirePendingShiftSwapRequests(ctx context.Context) error
	GetActiveEmployeeHandbookByEmployeeID(ctx context.Context, employeeID uuid.UUID) (GetActiveEmployeeHandbookByEmployeeIDRow, error)
	GetActiveHandbookTemplateByDepartment(ctx context.Context, departmentID uuid.UUID) (HandbookTemplate, error)
	GetActiveLeavePolicyByType(ctx context.Context, leaveType LeaveRequestTypeEnum) (LeavePolicy, error)
	GetAdminDashboardStatCards(ctx context.Context) (GetAdminDashboardStatCardsRow, error)
	// Returns the ID of the admin role.
	GetAdminRoleId(ctx context.Context) (uuid.UUID, error)
	GetAiGeneratedReport(ctx context.Context, id uuid.UUID) (AiGeneratedReport, error)
	GetAllAdminUsers(ctx context.Context) ([]CustomUser, error)
	GetAllClientsIDs(ctx context.Context) ([]uuid.UUID, error)
	GetAllTemplateItems(ctx context.Context) ([]TemplateItem, error)
	GetAppOrganizationProfile(ctx context.Context) (AppOrganizationProfile, error)
	GetAppointmentCard(ctx context.Context, clientID uuid.UUID) (GetAppointmentCardRow, error)
	GetAssignedEmployee(ctx context.Context, id uuid.UUID) (GetAssignedEmployeeRow, error)
	GetAttachmentById(ctx context.Context, argUuid uuid.UUID) (AttachmentFile, error)
	GetAttachmentsByUUIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]AttachmentFile, error)
	// Important: do NOT use contract.updated_at as a status effective date.
	// Any non-status update would shift the "approved" start forward and underbill.
	// Deduplicate identical status within 1 second windows (protects against rapid double updates)
	GetBillablePeriodsForContract(ctx context.Context, arg GetBillablePeriodsForContractParams) ([]GetBillablePeriodsForContractRow, error)
	GetCalendarEventByID(ctx context.Context, id uuid.UUID) (CalendarEvent, error)
	GetCalendarEventOverrideByMasterAndRecurrence(ctx context.Context, arg GetCalendarEventOverrideByMasterAndRecurrenceParams) (CalendarEvent, error)
	GetClientByIntakeFormID(ctx context.Context, intakeFormID *uuid.UUID) (ClientDetail, error)
	GetClientContract(ctx context.Context, id uuid.UUID) (GetClientContractRow, error)
	GetClientCoordinator(ctx context.Context, clientID uuid.UUID) ([]GetClientCoordinatorRow, error)
	GetClientCounts(ctx context.Context) (GetClientCountsRow, error)
	GetClientDetails(ctx context.Context, id uuid.UUID) (GetClientDetailsRow, error)
	GetClientDiagnosis(ctx context.Context, arg GetClientDiagnosisParams) (ClientDiagnosis, error)
	GetClientGoalByIDAndClientID(ctx context.Context, arg GetClientGoalByIDAndClientIDParams) (ClientGoal, error)
	GetClientLatestStatusHistory(ctx context.Context, clientID uuid.UUID) (GetClientLatestStatusHistoryRow, error)
	GetClientMedicationOrder(ctx context.Context, arg GetClientMedicationOrderParams) (GetClientMedicationOrderRow, error)
	GetClientPageCounts(ctx context.Context, clientID uuid.UUID) (GetClientPageCountsRow, error)
	GetClientRelatedEmails(ctx context.Context, clientID uuid.UUID) ([]*string, error)
	GetClientSender(ctx context.Context, id uuid.UUID) (Sender, error)
	GetClientStatusCounts(ctx context.Context) (GetClientStatusCountsRow, error)
	GetCompletedPaymentSum(ctx context.Context, invoiceID uuid.UUID) (float64, error)
	GetContractAudit(ctx context.Context, contractID uuid.UUID) ([]GetContractAuditRow, error)
	GetCurrentCycleDraftEvaluationByClientAndEmployee(ctx context.Context, arg GetCurrentCycleDraftEvaluationByClientAndEmployeeParams) (ClientGoalEvaluation, error)
	GetDepartment(ctx context.Context, id uuid.UUID) (Department, error)
	GetDepartmentByName(ctx context.Context, name string) (Department, error)
	GetDraftGoalEvaluationByClientAndDate(ctx context.Context, arg GetDraftGoalEvaluationByClientAndDateParams) (ClientGoalEvaluation, error)
	GetEmergencyContact(ctx context.Context, id uuid.UUID) (ClientEmergencyContact, error)
	GetEmployeeContractDetails(ctx context.Context, id uuid.UUID) (GetEmployeeContractDetailsRow, error)
	GetEmployeeCounts(ctx context.Context) (GetEmployeeCountsRow, error)
	GetEmployeeHandbookByID(ctx context.Context, id uuid.UUID) (EmployeeHandbook, error)
	GetEmployeeHandbookDetailsByID(ctx context.Context, id uuid.UUID) (GetEmployeeHandbookDetailsByIDRow, error)
	GetEmployeeProfileByID(ctx context.Context, id uuid.UUID) (GetEmployeeProfileByIDRow, error)
	GetEmployeeProfileByUserID(ctx context.Context, id uuid.UUID) (GetEmployeeProfileByUserIDRow, error)
	GetEmployeeSchedules(ctx context.Context, arg GetEmployeeSchedulesParams) ([]GetEmployeeSchedulesRow, error)
	GetGlobalOrganisationCounts(ctx context.Context) (GetGlobalOrganisationCountsRow, error)
	GetGoalEvaluationByID(ctx context.Context, id uuid.UUID) (GetGoalEvaluationByIDRow, error)
	GetGoalEvaluationItems(ctx context.Context, evaluationID uuid.UUID) ([]GetGoalEvaluationItemsRow, error)
	GetHandbookStepByID(ctx context.Context, id uuid.UUID) (HandbookStep, error)
	GetHandbookTemplateByID(ctx context.Context, id uuid.UUID) (HandbookTemplate, error)
	GetIncident(ctx context.Context, id uuid.UUID) (GetIncidentRow, error)
	GetIncidentCounts(ctx context.Context) (GetIncidentCountsRow, error)
	GetIntakeForm(ctx context.Context, id uuid.UUID) (IntakeForm, error)
	GetIntakeFormByRegistrationFormID(ctx context.Context, registrationFormID uuid.UUID) (IntakeForm, error)
	GetIntakeFormDetails(ctx context.Context, id uuid.UUID) (GetIntakeFormDetailsRow, error)
	GetIntakeFormTotals(ctx context.Context) (GetIntakeFormTotalsRow, error)
	GetIntakeMaturityAssessment(ctx context.Context, id uuid.UUID) (GetIntakeMaturityAssessmentRow, error)
	GetIntakeTopicsAssessments(ctx context.Context, intakeFormID uuid.UUID) ([]GetIntakeTopicsAssessmentsRow, error)
	GetInvoice(ctx context.Context, id uuid.UUID) (GetInvoiceRow, error)
	GetInvoiceAuditLogs(ctx context.Context, invoiceID uuid.UUID) ([]GetInvoiceAuditLogsRow, error)
	GetInvoiceSenderID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	GetLatestAuditHash(ctx context.Context) (string, error)
	GetLatestCompletedEvaluationByClient(ctx context.Context, clientID uuid.UUID) (GetLatestCompletedEvaluationByClientRow, error)
	GetLatestDraftEvaluationByClient(ctx context.Context, clientID uuid.UUID) (GetLatestDraftEvaluationByClientRow, error)
	GetLeaveRequestStats(ctx context.Context) (GetLeaveRequestStatsRow, error)
	GetLocation(ctx context.Context, id uuid.UUID) (Location, error)
	GetMaxInvoiceSequenceForDate(ctx context.Context, date interface{}) (int64, error)
	GetMissingClientDocuments(ctx context.Context, clientID uuid.UUID) ([]string, error)
	GetMyLeaveRequestStats(ctx context.Context, employeeID uuid.UUID) (GetMyLeaveRequestStatsRow, error)
	GetNextActiveClientGoalSortOrder(ctx context.Context, clientID uuid.UUID) (int32, error)
	GetOrganisation(ctx context.Context, id uuid.UUID) (GetOrganisationRow, error)
	GetOrganisationCounts(ctx context.Context, id uuid.UUID) (GetOrganisationCountsRow, error)
	GetPayment(ctx context.Context, id uuid.UUID) (GetPaymentRow, error)
	GetPaymentWithInvoice(ctx context.Context, id uuid.UUID) (GetPaymentWithInvoiceRow, error)
	GetProgressReport(ctx context.Context, id uuid.UUID) (GetProgressReportRow, error)
	GetProgressReportsByDateRange(ctx context.Context, arg GetProgressReportsByDateRangeParams) ([]ProgressReport, error)
	GetRegistrationForm(ctx context.Context, id uuid.UUID) (GetRegistrationFormRow, error)
	GetRegistrationFormByToken(ctx context.Context, intakeToken *string) (RegistrationForm, error)
	GetScheduleById(ctx context.Context, id uuid.UUID) (GetScheduleByIdRow, error)
	GetScheduleForSwapValidation(ctx context.Context, id uuid.UUID) (GetScheduleForSwapValidationRow, error)
	GetSchedulesByLocationInRange(ctx context.Context, arg GetSchedulesByLocationInRangeParams) ([]GetSchedulesByLocationInRangeRow, error)
	GetSenderById(ctx context.Context, id uuid.UUID) (Sender, error)
	GetSenderContracts(ctx context.Context, senderID uuid.UUID) ([]Contract, error)
	GetSenderInvoiceTemplate(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	GetShiftByID(ctx context.Context, id uuid.UUID) (LocationShift, error)
	GetShiftSwapRequestByID(ctx context.Context, id uuid.UUID) (ShiftSwapRequest, error)
	GetShiftSwapRequestDetailsByID(ctx context.Context, id uuid.UUID) (GetShiftSwapRequestDetailsByIDRow, error)
	GetShiftsByLocationID(ctx context.Context, locationID uuid.UUID) ([]LocationShift, error)
	GetTemp2FaSecret(ctx context.Context, id uuid.UUID) (*string, error)
	GetTemplateItemsByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]uuid.UUID, error)
	GetTemplateItemsBySourceTable(ctx context.Context, dollar_1 []uuid.UUID) ([]TemplateItem, error)
	GetTopicByID(ctx context.Context, id uuid.UUID) (Topic, error)
	GetTopicLevel(ctx context.Context, arg GetTopicLevelParams) (GetTopicLevelRow, error)
	GetTotalPaidAmountByInvoice(ctx context.Context, invoiceID uuid.UUID) (float64, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserIDByEmployeeID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	// ---------- 4. USER-ROLE MAPPING ----------
	// Returns every role granted to a user.
	GetUserRoles(ctx context.Context, userID uuid.UUID) ([]GetUserRolesRow, error)
	GetVisibleEventByID(ctx context.Context, arg GetVisibleEventByIDParams) (CalendarEvent, error)
	GoalHasEvaluationItems(ctx context.Context, goalID uuid.UUID) (bool, error)
	HasActiveClientByIntakeFormID(ctx context.Context, intakeFormID *uuid.UUID) (bool, error)
	InsertBilledCalendarEvent(ctx context.Context, arg InsertBilledCalendarEventParams) (BilledCalendarEvent, error)
	InsertIncoicePdfUrl(ctx context.Context, arg InsertIncoicePdfUrlParams) (*uuid.UUID, error)
	ListActiveGoalSummariesByClientID(ctx context.Context, clientID uuid.UUID) ([]ListActiveGoalSummariesByClientIDRow, error)
	ListActiveGoalsByClientID(ctx context.Context, clientID uuid.UUID) ([]ClientGoal, error)
	ListActiveSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]ListActiveSessionsByUserIDRow, error)
	ListAiGeneratedReports(ctx context.Context, arg ListAiGeneratedReportsParams) ([]ListAiGeneratedReportsRow, error)
	ListAllIncidents(ctx context.Context, arg ListAllIncidentsParams) ([]ListAllIncidentsRow, error)
	ListAllLocations(ctx context.Context) ([]ListAllLocationsRow, error)
	ListAllLocationsPaginated(ctx context.Context, arg ListAllLocationsPaginatedParams) ([]ListAllLocationsPaginatedRow, error)
	// ---------- 2. PERMISSIONS ----------
	// Returns every permission ordered by id.
	ListAllPermissions(ctx context.Context) ([]Permission, error)
	// ---------- 3. ROLE-PERMISSION MAPPING ----------
	// Returns all permissions attached to a single role.
	ListAllRolePermissions(ctx context.Context, roleID uuid.UUID) ([]ListAllRolePermissionsRow, error)
	// Returns all approved contracts for a (client, sender) overlapping the billing period.
	ListApprovedContractsForClientSenderInPeriod(ctx context.Context, arg ListApprovedContractsForClientSenderInPeriodParams) ([]ListApprovedContractsForClientSenderInPeriodRow, error)
	ListAssignedEmployees(ctx context.Context, arg ListAssignedEmployeesParams) ([]ListAssignedEmployeesRow, error)
	ListAssignedSchedulesForEmployeeOnDate(ctx context.Context, arg ListAssignedSchedulesForEmployeeOnDateParams) ([]ListAssignedSchedulesForEmployeeOnDateRow, error)
	ListAttendeesByEventIDs(ctx context.Context, eventIds []uuid.UUID) ([]ListAttendeesByEventIDsRow, error)
	ListAuditRecords(ctx context.Context, arg ListAuditRecordsParams) ([]Audit, error)
	ListAuditRecordsByClientID(ctx context.Context, arg ListAuditRecordsByClientIDParams) ([]Audit, error)
	ListCarePlanTopics(ctx context.Context) ([]Topic, error)
	ListClientActiveApprovedContracts(ctx context.Context, clientID uuid.UUID) ([]ListClientActiveApprovedContractsRow, error)
	ListClientAppointmentsInRange(ctx context.Context, arg ListClientAppointmentsInRangeParams) ([]ListClientAppointmentsInRangeRow, error)
	ListClientAppointmentsStartingInRange(ctx context.Context, arg ListClientAppointmentsStartingInRangeParams) ([]ListClientAppointmentsStartingInRangeRow, error)
	ListClientContracts(ctx context.Context, arg ListClientContractsParams) ([]ListClientContractsRow, error)
	ListClientDetails(ctx context.Context, arg ListClientDetailsParams) ([]ListClientDetailsRow, error)
	ListClientDiagnoses(ctx context.Context, arg ListClientDiagnosesParams) ([]ListClientDiagnosesRow, error)
	ListClientDocuments(ctx context.Context, arg ListClientDocumentsParams) ([]ListClientDocumentsRow, error)
	ListClientLocationTransfer(ctx context.Context, arg ListClientLocationTransferParams) ([]ListClientLocationTransferRow, error)
	ListClientMedicationOrders(ctx context.Context, arg ListClientMedicationOrdersParams) ([]ListClientMedicationOrdersRow, error)
	ListClientNamesByIDs(ctx context.Context, clientIds []uuid.UUID) ([]ListClientNamesByIDsRow, error)
	// Returns distinct senders for a client that have at least one approved contract overlapping the billing period.
	ListClientSendersForPeriod(ctx context.Context, arg ListClientSendersForPeriodParams) ([]uuid.UUID, error)
	ListClientStatusHistory(ctx context.Context, arg ListClientStatusHistoryParams) ([]ClientStatusHistory, error)
	ListContractTypes(ctx context.Context) ([]ContractType, error)
	ListContracts(ctx context.Context, arg ListContractsParams) ([]ListContractsRow, error)
	ListContractsTobeReminded(ctx context.Context) ([]ListContractsTobeRemindedRow, error)
	ListDashboardRegistrationsToday(ctx context.Context, limit int32) ([]ListDashboardRegistrationsTodayRow, error)
	ListDepartments(ctx context.Context) ([]ListDepartmentsRow, error)
	ListDueScheduledOutOfCareMissingFinalEvaluation(ctx context.Context) ([]uuid.UUID, error)
	ListEducations(ctx context.Context, employeeID uuid.UUID) ([]EmployeeEducation, error)
	// Returns effective permissions after applying role inheritance and overrides.
	ListEffectiveUserPermissions(ctx context.Context, userID uuid.UUID) ([]ListEffectiveUserPermissionsRow, error)
	ListEligibleEmployeesForHandbookAssignment(ctx context.Context, arg ListEligibleEmployeesForHandbookAssignmentParams) ([]ListEligibleEmployeesForHandbookAssignmentRow, error)
	ListEmergencyContacts(ctx context.Context, arg ListEmergencyContactsParams) ([]ListEmergencyContactsRow, error)
	ListEmployeeAppointmentsInRange(ctx context.Context, arg ListEmployeeAppointmentsInRangeParams) ([]ListEmployeeAppointmentsInRangeRow, error)
	ListEmployeeCertifications(ctx context.Context, employeeID uuid.UUID) ([]Certification, error)
	ListEmployeeExperience(ctx context.Context, employeeID uuid.UUID) ([]EmployeeExperience, error)
	ListEmployeeHandbookAssignmentHistoryByEmployeeID(ctx context.Context, arg ListEmployeeHandbookAssignmentHistoryByEmployeeIDParams) ([]EmployeeHandbookAssignmentHistory, error)
	ListEmployeeHandbookAssignments(ctx context.Context, arg ListEmployeeHandbookAssignmentsParams) ([]ListEmployeeHandbookAssignmentsRow, error)
	ListEmployeeHandbookStepsByHandbookID(ctx context.Context, employeeHandbookID uuid.UUID) ([]ListEmployeeHandbookStepsByHandbookIDRow, error)
	ListEmployeeNamesByIDs(ctx context.Context, employeeIds []uuid.UUID) ([]ListEmployeeNamesByIDsRow, error)
	ListEmployeeProfile(ctx context.Context, arg ListEmployeeProfileParams) ([]ListEmployeeProfileRow, error)
	ListEmployeesByContractEndDate(ctx context.Context) ([]ListEmployeesByContractEndDateRow, error)
	ListEmployeesEligibleForDepartmentHandbookSeed(ctx context.Context, arg ListEmployeesEligibleForDepartmentHandbookSeedParams) ([]uuid.UUID, error)
	ListEmployeesWithContractHours(ctx context.Context, dollar_1 []uuid.UUID) ([]ListEmployeesWithContractHoursRow, error)
	ListExistingClientDocumentLabels(ctx context.Context, clientID uuid.UUID) ([]string, error)
	ListGoalEvaluationHistoryByClientAndGoal(ctx context.Context, arg ListGoalEvaluationHistoryByClientAndGoalParams) ([]ListGoalEvaluationHistoryByClientAndGoalRow, error)
	ListHandbookStepsByTemplate(ctx context.Context, templateID uuid.UUID) ([]HandbookStep, error)
	ListHandbookTemplatesByDepartment(ctx context.Context, departmentID uuid.UUID) ([]HandbookTemplate, error)
	ListInCareClients(ctx context.Context, arg ListInCareClientsParams) ([]ListInCareClientsRow, error)
	ListIncidentReportRecipientEmails(ctx context.Context, clientID uuid.UUID) ([]*string, error)
	ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]ListIncidentsRow, error)
	// ---------- 5. USER-PERMISSION OVERRIDES ----------
	// Returns permissions inherited from the user's assigned role.
	ListInheritedUserPermissions(ctx context.Context, userID uuid.UUID) ([]ListInheritedUserPermissionsRow, error)
	ListIntakeForms(ctx context.Context, arg ListIntakeFormsParams) ([]ListIntakeFormsRow, error)
	ListIntakeTopicsAssessmentsByIntake(ctx context.Context, arg ListIntakeTopicsAssessmentsByIntakeParams) ([]ListIntakeTopicsAssessmentsByIntakeRow, error)
	ListInvoiceLinesByInvoice(ctx context.Context, invoiceID uuid.UUID) ([]InvoiceLine, error)
	// ==========================================
	// Invoicing Helpers
	// ==========================================
	// Returns distinct (sender_id, client_id) pairs that have at least one approved contract overlapping the billing period.
	ListInvoiceTargetsForPeriod(ctx context.Context, arg ListInvoiceTargetsForPeriodParams) ([]ListInvoiceTargetsForPeriodRow, error)
	ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]ListInvoicesRow, error)
	ListLateArrivalsPaginated(ctx context.Context, arg ListLateArrivalsPaginatedParams) ([]ListLateArrivalsPaginatedRow, error)
	ListLatestCompletedGoalProgressByClient(ctx context.Context, clientID uuid.UUID) ([]ListLatestCompletedGoalProgressByClientRow, error)
	ListLatestPayments(ctx context.Context) ([]ListLatestPaymentsRow, error)
	ListLeaveBalancesPaginated(ctx context.Context, arg ListLeaveBalancesPaginatedParams) ([]ListLeaveBalancesPaginatedRow, error)
	ListLeaveRequestsPaginated(ctx context.Context, arg ListLeaveRequestsPaginatedParams) ([]ListLeaveRequestsPaginatedRow, error)
	ListLocations(ctx context.Context, organisationID uuid.UUID) ([]ListLocationsRow, error)
	ListLocationsPaginated(ctx context.Context, arg ListLocationsPaginatedParams) ([]ListLocationsPaginatedRow, error)
	ListMyLateArrivalsPaginated(ctx context.Context, arg ListMyLateArrivalsPaginatedParams) ([]ListMyLateArrivalsPaginatedRow, error)
	ListMyLeaveBalancesPaginated(ctx context.Context, arg ListMyLeaveBalancesPaginatedParams) ([]ListMyLeaveBalancesPaginatedRow, error)
	ListMyLeaveRequestsPaginated(ctx context.Context, arg ListMyLeaveRequestsPaginatedParams) ([]ListMyLeaveRequestsPaginatedRow, error)
	ListMyShiftSwapRequests(ctx context.Context, requesterEmployeeID uuid.UUID) ([]ListMyShiftSwapRequestsRow, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListOrganisations(ctx context.Context) ([]ListOrganisationsRow, error)
	ListOrganisationsPaginated(ctx context.Context, arg ListOrganisationsPaginatedParams) ([]ListOrganisationsPaginatedRow, error)
	ListPayments(ctx context.Context, invoiceID uuid.UUID) ([]ListPaymentsRow, error)
	ListProgressReports(ctx context.Context, arg ListProgressReportsParams) ([]ListProgressReportsRow, error)
	ListRecentDraftEvaluationsByEmployee(ctx context.Context, arg ListRecentDraftEvaluationsByEmployeeParams) ([]ListRecentDraftEvaluationsByEmployeeRow, error)
	ListRecentSubmittedEvaluationsByEmployee(ctx context.Context, arg ListRecentSubmittedEvaluationsByEmployeeParams) ([]ListRecentSubmittedEvaluationsByEmployeeRow, error)
	ListRegistrationForms(ctx context.Context, arg ListRegistrationFormsParams) ([]ListRegistrationFormsRow, error)
	ListRemindersByEventID(ctx context.Context, eventID uuid.UUID) ([]ListRemindersByEventIDRow, error)
	// Returns every role ordered by id with count of permissions and employees.
	ListRoles(ctx context.Context) ([]ListRolesRow, error)
	ListSenders(ctx context.Context, arg ListSendersParams) ([]Sender, error)
	ListSeriesExceptions(ctx context.Context, seriesIds []uuid.UUID) ([]CalendarEvent, error)
	ListSeriesExceptionsStartingInRange(ctx context.Context, arg ListSeriesExceptionsStartingInRangeParams) ([]CalendarEvent, error)
	ListShiftSwapRequestsPaginated(ctx context.Context, arg ListShiftSwapRequestsPaginatedParams) ([]ListShiftSwapRequestsPaginatedRow, error)
	ListSubmittedEvaluationsByClient(ctx context.Context, arg ListSubmittedEvaluationsByClientParams) ([]ListSubmittedEvaluationsByClientRow, error)
	ListTopAdminActions(ctx context.Context, limit int32) ([]ListTopAdminActionsRow, error)
	ListTopEmergencyContactsByClientID(ctx context.Context, clientID uuid.UUID) ([]ListTopEmergencyContactsByClientIDRow, error)
	// ==========================================
	// Invoicing Helpers
	// ==========================================
	// Returns appointments for a client that start within [start_date, end_date) and are not already billed (unless voided).
	ListUnbilledClientAppointmentsStartingInRange(ctx context.Context, arg ListUnbilledClientAppointmentsStartingInRangeParams) ([]ListUnbilledClientAppointmentsStartingInRangeRow, error)
	ListUpcomingAppointments(ctx context.Context, organizerEmployeeID uuid.UUID) ([]ListUpcomingAppointmentsRow, error)
	ListUpcomingEvaluationsForCoordinator(ctx context.Context, arg ListUpcomingEvaluationsForCoordinatorParams) ([]ListUpcomingEvaluationsForCoordinatorRow, error)
	ListUserIDsByEmployeeIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]uuid.UUID, error)
	// Returns explicit allow/deny overrides configured for a user.
	ListUserPermissionOverrides(ctx context.Context, userID uuid.UUID) ([]ListUserPermissionOverridesRow, error)
	ListVisibleMasterEvents(ctx context.Context, arg ListVisibleMasterEventsParams) ([]CalendarEvent, error)
	ListWaitingListClients(ctx context.Context, arg ListWaitingListClientsParams) ([]ListWaitingListClientsRow, error)
	// ==========================================
	// Work Approval Queue (Admin)
	// ==========================================
	ListWorkApprovalQueueOneOffAppointmentsStartingInRange(ctx context.Context, arg ListWorkApprovalQueueOneOffAppointmentsStartingInRangeParams) ([]CalendarEvent, error)
	ListWorkApprovalQueueRecurringMastersStartingBeforeEnd(ctx context.Context, arg ListWorkApprovalQueueRecurringMastersStartingBeforeEndParams) ([]CalendarEvent, error)
	// Audit table queries
	LockAuditHashChain(ctx context.Context) error
	LockIntakeFormByID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	LockLeaveBalanceByEmployeeYear(ctx context.Context, arg LockLeaveBalanceByEmployeeYearParams) (LeaveBalance, error)
	LockLeaveRequestByID(ctx context.Context, id uuid.UUID) (LeaveRequest, error)
	LockSchedulesByIDsForSwap(ctx context.Context, dollar_1 []uuid.UUID) ([]LockSchedulesByIDsForSwapRow, error)
	LockShiftSwapRequestForAdminDecision(ctx context.Context, id uuid.UUID) (ShiftSwapRequest, error)
	MarkEmployeeHandbookCompleted(ctx context.Context, id uuid.UUID) (EmployeeHandbook, error)
	MarkEmployeeHandbookStarted(ctx context.Context, id uuid.UUID) (EmployeeHandbook, error)
	MarkIncidentConfirmationEmailSent(ctx context.Context, id uuid.UUID) (int64, error)
	MarkNotificationAsRead(ctx context.Context, id uuid.UUID) (Notification, error)
	MarkShiftSwapConfirmed(ctx context.Context, arg MarkShiftSwapConfirmedParams) (ShiftSwapRequest, error)
	PublishHandbookTemplate(ctx context.Context, arg PublishHandbookTemplateParams) (HandbookTemplate, error)
	PutClientInCare(ctx context.Context, arg PutClientInCareParams) (ClientDetail, error)
	PutClientOutOfCare(ctx context.Context, arg PutClientOutOfCareParams) (ClientDetail, error)
	// Removes *all* permissions from the given role.
	RemovePermissionsFromRole(ctx context.Context, roleID uuid.UUID) error
	SearchEmployeesByNameOrEmail(ctx context.Context, search *string) ([]SearchEmployeesByNameOrEmailRow, error)
	SetAttachmentAsUsedorUnused(ctx context.Context, arg SetAttachmentAsUsedorUnusedParams) (AttachmentFile, error)
	SetAttachmentsAsUsedorUnusedByUUIDs(ctx context.Context, arg SetAttachmentsAsUsedorUnusedByUUIDsParams) ([]AttachmentFile, error)
	SetEmployeeProfilePicture(ctx context.Context, arg SetEmployeeProfilePictureParams) (CustomUser, error)
	StatusChangeCount(ctx context.Context) (int64, error)
	TotalDischargeCount(ctx context.Context) (int64, error)
	UpdateAppOrganizationProfile(ctx context.Context, arg UpdateAppOrganizationProfileParams) (AppOrganizationProfile, error)
	UpdateAppointmentCard(ctx context.Context, arg UpdateAppointmentCardParams) (AppointmentCard, error)
	UpdateAssignedEmployee(ctx context.Context, arg UpdateAssignedEmployeeParams) (AssignedEmployee, error)
	UpdateCalendarEvent(ctx context.Context, arg UpdateCalendarEventParams) (CalendarEvent, error)
	UpdateCalendarEventRRule(ctx context.Context, arg UpdateCalendarEventRRuleParams) error
	UpdateCalendarEventWorkApproval(ctx context.Context, arg UpdateCalendarEventWorkApprovalParams) error
	// -- name: UpdateClientDetails :one
	// UPDATE client_details
	// SET
	//     first_name = COALESCE (sqlc.narg('first_name'), first_name),
	//     last_name = COALESCE (sqlc.narg('last_name'), last_name),
	//     date_of_birth = COALESCE (sqlc.narg('date_of_birth'), date_of_birth),
	//     "identity" = COALESCE (sqlc.narg('identity'), "identity"),
	//     bsn = COALESCE (sqlc.narg('bsn'), bsn),
	//     bsn_verified_by = COALESCE (sqlc.narg('bsn_verified_by'), bsn_verified_by),
	//     email = COALESCE (sqlc.narg('email'), email),
	//     phone_number = COALESCE (sqlc.narg('phone_number'), phone_number),
	//     gender = COALESCE (sqlc.narg('gender'), gender),
	//     filenumber = COALESCE (sqlc.narg('filenumber'), filenumber),
	//     sender_id = COALESCE (sqlc.narg('sender_id'), sender_id),
	//     location_id = COALESCE (sqlc.narg('location_id'), location_id),
	//     departure_reason = COALESCE (sqlc.narg('departure_reason'), departure_reason),
	//     departure_report = COALESCE (sqlc.narg('departure_report'), departure_report),
	//     legal_measure = COALESCE (sqlc.narg('legal_measure'), legal_measure),
	//     education_currently_enrolled = COALESCE (sqlc.narg('education_currently_enrolled'), education_currently_enrolled),
	//     education_institution = COALESCE (sqlc.narg('education_institution'), education_institution),
	//     education_mentor_name = COALESCE (sqlc.narg('education_mentor_name'), education_mentor_name),
	//     education_mentor_phone = COALESCE (sqlc.narg('education_mentor_phone'), education_mentor_phone),
	//     education_mentor_email = COALESCE (sqlc.narg('education_mentor_email'), education_mentor_email),
	//     education_additional_notes = COALESCE (sqlc.narg('education_additional_notes'), education_additional_notes),
	//     education_level = COALESCE (sqlc.narg('education_level'), education_level),
	//     work_currently_employed = COALESCE (sqlc.narg('work_currently_employed'), work_currently_employed),
	//     work_current_employer = COALESCE (sqlc.narg('work_current_employer'), work_current_employer),
	//     work_current_employer_phone = COALESCE (sqlc.narg('work_current_employer_phone'), work_current_employer_phone),
	//     work_current_employer_email = COALESCE (sqlc.narg('work_current_employer_email'), work_current_employer_email),
	//     work_current_position = COALESCE (sqlc.narg('work_current_position'), work_current_position),
	//     work_start_date = COALESCE (sqlc.narg('work_start_date'), work_start_date),
	//     work_additional_notes = COALESCE (sqlc.narg('work_additional_notes'), work_additional_notes),
	//     living_situation = COALESCE (sqlc.narg('living_situation'), living_situation),
	//     living_situation_notes = COALESCE (sqlc.narg('living_situation_notes'), living_situation_notes),
	//     nationality = COALESCE (sqlc.narg('nationality'), nationality)
	// WHERE id = $1
	// RETURNING *;
	UpdateClientDetailsV2(ctx context.Context, arg UpdateClientDetailsV2Params) (ClientDetail, error)
	UpdateClientDiagnosis(ctx context.Context, arg UpdateClientDiagnosisParams) (ClientDiagnosis, error)
	UpdateClientGoalByID(ctx context.Context, arg UpdateClientGoalByIDParams) (ClientGoal, error)
	UpdateClientMedicationOrder(ctx context.Context, arg UpdateClientMedicationOrderParams) (ClientMedicationOrder, error)
	UpdateClientStatus(ctx context.Context, arg UpdateClientStatusParams) (ClientDetail, error)
	UpdateContract(ctx context.Context, arg UpdateContractParams) (Contract, error)
	UpdateContractStatus(ctx context.Context, arg UpdateContractStatusParams) (Contract, error)
	UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error)
	UpdateEmergencyContact(ctx context.Context, arg UpdateEmergencyContactParams) (ClientEmergencyContact, error)
	UpdateEmployeeCertification(ctx context.Context, arg UpdateEmployeeCertificationParams) (Certification, error)
	UpdateEmployeeEducation(ctx context.Context, arg UpdateEmployeeEducationParams) (EmployeeEducation, error)
	UpdateEmployeeExperience(ctx context.Context, arg UpdateEmployeeExperienceParams) (EmployeeExperience, error)
	UpdateEmployeeIsSubcontractor(ctx context.Context, arg UpdateEmployeeIsSubcontractorParams) (EmployeeProfile, error)
	UpdateEmployeePassword(ctx context.Context, arg UpdateEmployeePasswordParams) (uuid.UUID, error)
	UpdateEmployeeProfile(ctx context.Context, arg UpdateEmployeeProfileParams) (EmployeeProfile, error)
	UpdateGoalEvaluation(ctx context.Context, arg UpdateGoalEvaluationParams) (ClientGoalEvaluation, error)
	UpdateHandbookStepByID(ctx context.Context, arg UpdateHandbookStepByIDParams) (HandbookStep, error)
	UpdateHandbookStepSortOrder(ctx context.Context, arg UpdateHandbookStepSortOrderParams) error
	UpdateHandbookTemplateMetadata(ctx context.Context, arg UpdateHandbookTemplateMetadataParams) (HandbookTemplate, error)
	UpdateIncident(ctx context.Context, arg UpdateIncidentParams) (Incident, error)
	UpdateIncidentFileUrl(ctx context.Context, arg UpdateIncidentFileUrlParams) (*string, error)
	UpdateIntakeConclusion(ctx context.Context, arg UpdateIntakeConclusionParams) (IntakeForm, error)
	UpdateIntakeForm(ctx context.Context, arg UpdateIntakeFormParams) (IntakeForm, error)
	UpdateIntakeTopicsAssessment(ctx context.Context, arg UpdateIntakeTopicsAssessmentParams) (IntakeTopicAssessment, error)
	UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) (Invoice, error)
	UpdateInvoiceLine(ctx context.Context, arg UpdateInvoiceLineParams) (InvoiceLine, error)
	UpdateInvoiceRun(ctx context.Context, arg UpdateInvoiceRunParams) (InvoiceRun, error)
	UpdateInvoiceRunItem(ctx context.Context, arg UpdateInvoiceRunItemParams) (InvoiceRunItem, error)
	UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error)
	UpdateLeaveRequestDecision(ctx context.Context, arg UpdateLeaveRequestDecisionParams) (LeaveRequest, error)
	UpdateLeaveRequestEditableFields(ctx context.Context, arg UpdateLeaveRequestEditableFieldsParams) (LeaveRequest, error)
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error)
	UpdateOrganisation(ctx context.Context, arg UpdateOrganisationParams) (Organisation, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (InvoicePaymentHistory, error)
	UpdateProgressReport(ctx context.Context, arg UpdateProgressReportParams) (ProgressReport, error)
	UpdateRegistrationForm(ctx context.Context, arg UpdateRegistrationFormParams) (RegistrationForm, error)
	UpdateRegistrationFormIntakeDate(ctx context.Context, arg UpdateRegistrationFormIntakeDateParams) (RegistrationForm, error)
	UpdateRegistrationFormStatus(ctx context.Context, arg UpdateRegistrationFormStatusParams) (RegistrationForm, error)
	UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (UpdateScheduleRow, error)
	UpdateScheduleEmployeeAssignment(ctx context.Context, arg UpdateScheduleEmployeeAssignmentParams) error
	UpdateSender(ctx context.Context, arg UpdateSenderParams) (Sender, error)
	UpdateShift(ctx context.Context, arg UpdateShiftParams) (LocationShift, error)
	UpdateShiftSwapAdminDecision(ctx context.Context, arg UpdateShiftSwapAdminDecisionParams) (ShiftSwapRequest, error)
	UpdateShiftSwapStatusAfterRecipientResponse(ctx context.Context, arg UpdateShiftSwapStatusAfterRecipientResponseParams) (ShiftSwapRequest, error)
	UpsertCalendarEventOverride(ctx context.Context, arg UpsertCalendarEventOverrideParams) (CalendarEvent, error)
	UpsertGoalEvaluationItem(ctx context.Context, arg UpsertGoalEvaluationItemParams) (ClientGoalEvaluationItem, error)
	// Join to get the client location name
	UpsertMainCoordinator(ctx context.Context, arg UpsertMainCoordinatorParams) (UpsertMainCoordinatorRow, error)
	UpsertMainCoordinatorByEmployee(ctx context.Context, arg UpsertMainCoordinatorByEmployeeParams) error
	UrgentCasesCount(ctx context.Context) (int64, error)
	VoidBilledCalendarEventsByInvoice(ctx context.Context, invoiceID uuid.UUID) error
	WaiveActiveEmployeeHandbooksByEmployeeID(ctx context.Context, employeeID uuid.UUID) error
	WaiveEmployeeHandbookByID(ctx context.Context, id uuid.UUID) (EmployeeHandbook, error)
}

var _ Querier = (*Queries)(nil)
