// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: roles.sql

package db

import (
	"context"
)

const checkRolePermission = `-- name: CheckRolePermission :one
SELECT EXISTS (
    SELECT 1
    FROM role_permissions rp
    JOIN permissions p ON p.id = rp.permission_id
    WHERE rp.role_id = $1
    AND p.resource = $2
    AND p.name = $3
) AS exists
`

type CheckRolePermissionParams struct {
	RoleID   int32  `json:"role_id"`
	Resource string `json:"resource"`
	Name     string `json:"name"`
}

func (q *Queries) CheckRolePermission(ctx context.Context, arg CheckRolePermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkRolePermission, arg.RoleID, arg.Resource, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getPermissionsByRoleID = `-- name: GetPermissionsByRoleID :many
SELECT p.id, p.name, p.resource
FROM permissions p
JOIN role_permissions rp ON p.id = rp.permission_id
WHERE rp.role_id = $1
`

func (q *Queries) GetPermissionsByRoleID(ctx context.Context, roleID int32) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getPermissionsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Name, &i.Resource); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
