// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addPermissionToRole = `-- name: AddPermissionToRole :exec
INSERT INTO role_permissions (role_id, permission_id, scope)
VALUES ($1, $2, $3)
`

type AddPermissionToRoleParams struct {
	RoleID       uuid.UUID            `json:"role_id"`
	PermissionID uuid.UUID            `json:"permission_id"`
	Scope        *PermissionScopeEnum `json:"scope"`
}

// Insert one permission grant while replacing a role's grants transactionally.
func (q *Queries) AddPermissionToRole(ctx context.Context, arg AddPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, addPermissionToRole, arg.RoleID, arg.PermissionID, arg.Scope)
	return err
}

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO user_roles (user_id, role_id)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET role_id = $2
`

type AssignRoleToUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.Exec(ctx, assignRoleToUser, arg.UserID, arg.RoleID)
	return err
}

const checkUserPermission = `-- name: CheckUserPermission :one

SELECT EXISTS (
    SELECT 1
    FROM user_roles ur
    JOIN role_permissions rp ON rp.role_id = ur.role_id
    JOIN permissions p ON p.id = rp.permission_id
    WHERE ur.user_id = $1
      AND p.name = $2
) AS has_permission
`

type CheckUserPermissionParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

// ---------- 6. CHECK UTILITIES ----------
// Returns whether the user's assigned role grants the named permission.
func (q *Queries) CheckUserPermission(ctx context.Context, arg CheckUserPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserPermission, arg.UserID, arg.Name)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const createRole = `-- name: CreateRole :one
/*
 *  RBAC – Role & Permission Management
 *  This file contains all sqlc queries for the simple role-based
 *  access-control system.  They are grouped in the following order:
 *    1. Core roles
 *    2. Core permissions
 *    3. Role <-> Permission mapping
 *    4. User <-> Role mapping
 *    5. User <-> Permission mapping
 *    6. Read queries
 *    7. Helper utilities
 *
 *  sqlc will generate Go types and funcs named after the ` + "`" + `-- name:` + "`" + ` tags.
 */


INSERT INTO roles (name, description)
VALUES ($1, $2)
RETURNING id, name, description
`

type CreateRoleParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

// ---------- 1. ROLES ----------
// Insert a new role and return the created row.
func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Name, arg.Description)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const getAdminRoleId = `-- name: GetAdminRoleId :one
SELECT id
FROM roles
WHERE name = 'admin'
`

// Returns the ID of the admin role.
func (q *Queries) GetAdminRoleId(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getAdminRoleId)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserRoles = `-- name: GetUserRoles :many

SELECT r.id, r.name
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = $1
`

type GetUserRolesRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// ---------- 4. USER-ROLE MAPPING ----------
// Returns every role granted to a user.
func (q *Queries) GetUserRoles(ctx context.Context, userID uuid.UUID) ([]GetUserRolesRow, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserRolesRow{}
	for rows.Next() {
		var i GetUserRolesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPermissions = `-- name: ListAllPermissions :many

SELECT id, name, group_key, section_key, display_name, description, is_scoped
FROM permissions
ORDER BY group_key, section_key, name
`

// ---------- 2. PERMISSIONS ----------
// Returns every permission ordered by id.
func (q *Queries) ListAllPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listAllPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GroupKey,
			&i.SectionKey,
			&i.DisplayName,
			&i.Description,
			&i.IsScoped,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRolePermissions = `-- name: ListAllRolePermissions :many

SELECT p.id   AS permission_id,
       p.name AS permission_name,
       p.is_scoped,
       rp.scope
FROM role_permissions rp
JOIN permissions p ON p.id = rp.permission_id
WHERE rp.role_id = $1
ORDER BY p.id
`

type ListAllRolePermissionsRow struct {
	PermissionID   uuid.UUID            `json:"permission_id"`
	PermissionName string               `json:"permission_name"`
	IsScoped       bool                 `json:"is_scoped"`
	Scope          *PermissionScopeEnum `json:"scope"`
}

// ---------- 3. ROLE-PERMISSION MAPPING ----------
// Returns all permissions attached to a single role.
func (q *Queries) ListAllRolePermissions(ctx context.Context, roleID uuid.UUID) ([]ListAllRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, listAllRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllRolePermissionsRow{}
	for rows.Next() {
		var i ListAllRolePermissionsRow
		if err := rows.Scan(
			&i.PermissionID,
			&i.PermissionName,
			&i.IsScoped,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEffectiveUserPermissions = `-- name: ListEffectiveUserPermissions :many

SELECT p.id AS permission_id,
       p.name AS permission_name
FROM user_roles ur
JOIN role_permissions rp ON rp.role_id = ur.role_id
JOIN permissions p ON p.id = rp.permission_id
WHERE ur.user_id = $1
ORDER BY p.id
`

type ListEffectiveUserPermissionsRow struct {
	PermissionID   uuid.UUID `json:"permission_id"`
	PermissionName string    `json:"permission_name"`
}

// ---------- 5. USER PERMISSIONS ----------
// Returns permissions granted by the user's assigned role.
func (q *Queries) ListEffectiveUserPermissions(ctx context.Context, userID uuid.UUID) ([]ListEffectiveUserPermissionsRow, error) {
	rows, err := q.db.Query(ctx, listEffectiveUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEffectiveUserPermissionsRow{}
	for rows.Next() {
		var i ListEffectiveUserPermissionsRow
		if err := rows.Scan(&i.PermissionID, &i.PermissionName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT 
    r.id,
    r.name,
    r.description,
    COALESCE(COUNT(DISTINCT rp.permission_id), 0)::BIGINT AS permission_count,
    COALESCE(COUNT(DISTINCT ep.id), 0)::BIGINT AS employee_count
FROM roles r
LEFT JOIN role_permissions rp ON r.id = rp.role_id
LEFT JOIN user_roles ur ON r.id = ur.role_id
LEFT JOIN employee_profile ep ON ep.user_id = ur.user_id
GROUP BY r.id, r.name, r.description
ORDER BY r.id
`

type ListRolesRow struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Description     *string   `json:"description"`
	PermissionCount int64     `json:"permission_count"`
	EmployeeCount   int64     `json:"employee_count"`
}

// Returns every role ordered by id with count of permissions and employees.
func (q *Queries) ListRoles(ctx context.Context) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesRow{}
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PermissionCount,
			&i.EmployeeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePermissionsFromRole = `-- name: RemovePermissionsFromRole :exec
DELETE FROM role_permissions
WHERE role_id = $1
`

// Removes *all* permissions from the given role.
func (q *Queries) RemovePermissionsFromRole(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removePermissionsFromRole, roleID)
	return err
}
