// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package db

import (
	"context"
)

const getAppOrganizationProfile = `-- name: GetAppOrganizationProfile :one
SELECT singleton, name, default_timezone, email, phone_number, website, hq_street, hq_house_number, hq_house_number_addition, hq_postal_code, hq_city, created_at, updated_at
FROM app_organization_profile
WHERE singleton = TRUE
LIMIT 1
`

func (q *Queries) GetAppOrganizationProfile(ctx context.Context) (AppOrganizationProfile, error) {
	row := q.db.QueryRow(ctx, getAppOrganizationProfile)
	var i AppOrganizationProfile
	err := row.Scan(
		&i.Singleton,
		&i.Name,
		&i.DefaultTimezone,
		&i.Email,
		&i.PhoneNumber,
		&i.Website,
		&i.HqStreet,
		&i.HqHouseNumber,
		&i.HqHouseNumberAddition,
		&i.HqPostalCode,
		&i.HqCity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAppOrganizationProfile = `-- name: UpdateAppOrganizationProfile :one
UPDATE app_organization_profile
SET
    name = $1,
    default_timezone = $2,
    email = $3,
    phone_number = $4,
    website = $5,
    hq_street = $6,
    hq_house_number = $7,
    hq_house_number_addition = $8,
    hq_postal_code = $9,
    hq_city = $10,
    updated_at = CURRENT_TIMESTAMP
WHERE singleton = TRUE
RETURNING singleton, name, default_timezone, email, phone_number, website, hq_street, hq_house_number, hq_house_number_addition, hq_postal_code, hq_city, created_at, updated_at
`

type UpdateAppOrganizationProfileParams struct {
	Name                  string  `json:"name"`
	DefaultTimezone       string  `json:"default_timezone"`
	Email                 *string `json:"email"`
	PhoneNumber           *string `json:"phone_number"`
	Website               *string `json:"website"`
	HqStreet              *string `json:"hq_street"`
	HqHouseNumber         *string `json:"hq_house_number"`
	HqHouseNumberAddition *string `json:"hq_house_number_addition"`
	HqPostalCode          *string `json:"hq_postal_code"`
	HqCity                *string `json:"hq_city"`
}

func (q *Queries) UpdateAppOrganizationProfile(ctx context.Context, arg UpdateAppOrganizationProfileParams) (AppOrganizationProfile, error) {
	row := q.db.QueryRow(ctx, updateAppOrganizationProfile,
		arg.Name,
		arg.DefaultTimezone,
		arg.Email,
		arg.PhoneNumber,
		arg.Website,
		arg.HqStreet,
		arg.HqHouseNumber,
		arg.HqHouseNumberAddition,
		arg.HqPostalCode,
		arg.HqCity,
	)
	var i AppOrganizationProfile
	err := row.Scan(
		&i.Singleton,
		&i.Name,
		&i.DefaultTimezone,
		&i.Email,
		&i.PhoneNumber,
		&i.Website,
		&i.HqStreet,
		&i.HqHouseNumber,
		&i.HqHouseNumberAddition,
		&i.HqPostalCode,
		&i.HqCity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
