// Code generated by MockGen. DO NOT EDIT.
// Source: maicare_go/bucket (interfaces: ObjectStorageInterface)
//
// Generated by this command:
//
//	mockgen -package bucketmocks -destination=../bucket/mocks/bucket_mock.go maicare_go/bucket ObjectStorageInterface
//

// Package bucketmocks is a generated GoMock package.
package bucketmocks

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockObjectStorageInterface is a mock of ObjectStorageInterface interface.
type MockObjectStorageInterface struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorageInterfaceMockRecorder
	isgomock struct{}
}

// MockObjectStorageInterfaceMockRecorder is the mock recorder for MockObjectStorageInterface.
type MockObjectStorageInterfaceMockRecorder struct {
	mock *MockObjectStorageInterface
}

// NewMockObjectStorageInterface creates a new mock instance.
func NewMockObjectStorageInterface(ctrl *gomock.Controller) *MockObjectStorageInterface {
	mock := &MockObjectStorageInterface{ctrl: ctrl}
	mock.recorder = &MockObjectStorageInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorageInterface) EXPECT() *MockObjectStorageInterfaceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockObjectStorageInterface) Delete(ctx context.Context, objectKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, objectKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockObjectStorageInterfaceMockRecorder) Delete(ctx, objectKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockObjectStorageInterface)(nil).Delete), ctx, objectKey)
}

// GeneratePresignedURL mocks base method.
func (m *MockObjectStorageInterface) GeneratePresignedURL(ctx context.Context, objectKey string, expiry time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePresignedURL", ctx, objectKey, expiry)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePresignedURL indicates an expected call of GeneratePresignedURL.
func (mr *MockObjectStorageInterfaceMockRecorder) GeneratePresignedURL(ctx, objectKey, expiry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePresignedURL", reflect.TypeOf((*MockObjectStorageInterface)(nil).GeneratePresignedURL), ctx, objectKey, expiry)
}

// Upload mocks base method.
func (m *MockObjectStorageInterface) Upload(ctx context.Context, file multipart.File, filename, contentType string) (string, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, file, filename, contentType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Upload indicates an expected call of Upload.
func (mr *MockObjectStorageInterfaceMockRecorder) Upload(ctx, file, filename, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockObjectStorageInterface)(nil).Upload), ctx, file, filename, contentType)
}
