-- Employee profile queries have been separated into context-specific files:
--
-- - employee_profile_crud.sql: Basic CRUD operations (Create, Read, Update, Delete)
-- - employee_profile_education.sql: Education-related queries
-- - employee_profile_experience.sql: Work experience queries
-- - employee_profile_certifications.sql: Certification management queries
-- - employee_profile_contracts.sql: Contract details and subcontractor status queries
-- - employee_profile_utility.sql: Utility queries (search, counts, user lookups, etc.)
--
-- This separation improves maintainability and organization of the database queries.
-- Please import the appropriate file for the functionality you need.