-- name: CreateRegistrationForm :one
INSERT INTO registration_form (
    client_first_name,
    client_last_name,
    client_bsn_number,
    client_gender,
    client_nationality,
    client_phone_number,
    client_email,
    client_street,
    client_house_number,
    client_postal_code,
    client_city,
    referrer_first_name,
    referrer_last_name,
    referrer_organization,
    referrer_job_title,
    referrer_phone_number,
    referrer_email,
    guardian1_first_name,
    guardian1_last_name,
    guardian1_relationship,
    guardian1_phone_number,
    guardian1_email,
    guardian2_first_name,
    guardian2_last_name,
    guardian2_relationship,
    guardian2_phone_number,
    guardian2_email,
    education_institution,
    education_mentor_name,
    education_mentor_phone,
    education_mentor_email,
    education_currently_enrolled,
    education_additional_notes,
    care_protected_living,
    care_assisted_independent_living,
    care_room_training_center,
    care_ambulatory_guidance,
    risk_aggressive_behavior,
    risk_suicidal_selfharm,
    risk_substance_abuse,
    risk_psychiatric_issues,
    risk_criminal_history,
    risk_flight_behavior,
    risk_weapon_possession,
    risk_sexual_behavior,
    risk_day_night_rhythm,
    risk_other,
    risk_other_description,
    risk_additional_notes,
    document_referral,
    document_education_report,
    document_psychiatric_report,
    document_diagnosis,
    document_safety_plan,
    document_id_copy,
    application_date,
    referrer_signature
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19,
    $20, $21, $22, $23, $24, $25, $26, $27, $28,
    $29, $30, $31, $32, $33, $34, $35, $36, $37,
    $38, $39, $40, $41, $42, $43, $44, $45, $46,
    $47, $48, $49, $50, $51, $52, $53, $54, $55,
    $56, $57
) RETURNING *;